/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-12-17 06:01:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.ea.newReport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hanaph.gw.co.common.utils.StringUtil;
import com.hanaph.gw.pe.member.vo.MemberVO;
import com.hanaph.gw.pe.member.vo.MemberVO;
import javax.servlet.http.HttpSession;

public final class step2approvalMemberIframe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1424677116691L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1429838623000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
com.hanaph.gw.co.common.utils.Environment env = new com.hanaph.gw.co.common.utils.Environment();
	
	String HTTPS_GROUP_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_GROUP_ROOT = env.getValue("https.root_dir.url");
	String GROUP_WEB_ROOT = env.getValue("web_root_dir.url");
	String GROUP_ROOT = env.getValue("root_dir.url");
	String JDBC_URL = env.getValue("jdbc.url");
	
	
      out.write('\r');
      out.write('\n');

	//소속사용자
	List<MemberVO> memberList = (List<MemberVO>)request.getAttribute("memberList");
	String emp_ko_nm = StringUtil.nvl((String)request.getAttribute("emp_ko_nm"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>하나제약 그룹웨어</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/dtree.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui-1.10.4.custom.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery.bpopup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/dtree.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/formCheck.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction goSearch(){\r\n");
      out.write("\t\t\tif(formCheck.isNull(document.getElementById(\"emp_ko_nm\"), \"성명을 입력하여 주십시오.\")){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(formCheck.containsChars(document.getElementById(\"emp_ko_nm\").value, \"%\")){\r\n");
      out.write("\t\t\t\t alert(\"특수문자를 사용할수 없습니다\");\r\n");
      out.write("\t\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"frm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//직원 checkbox 선택\r\n");
      out.write("\t\tfunction goApprovalTarget() {\r\n");
      out.write("\t\t \t   \r\n");
      out.write("\t\t    var chkCnt = checkCount();\r\n");
      out.write("\t\t    if(chkCnt > 0) {\r\n");
      out.write("\t\t    \tparent.approvalMemberTarget.addApprovalMultiRow();\r\n");
      out.write("\t\t \t} else {\r\n");
      out.write("\t\t        alert(\"임직원을 선택해주세요.\");\r\n");
      out.write("\t\t        return;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction allUnCheck() {\r\n");
      out.write("\t  \t \tvar objTable = document.getElementById(\"tbl\");\r\n");
      out.write("\t  \t \tvar lastRow = objTable.rows.length+1;\r\n");
      out.write("\t  \t \tfor(var i = lastRow; i > 1; i--) {\r\n");
      out.write("\t  \t  \t\tdocument.getElementsByTagName(\"TR\")[i].cells[0].firstChild.checked = false;\r\n");
      out.write("\t  \t \t}\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \tfunction checkCount() {\r\n");
      out.write("\t\t \tvar objTable = document.getElementById(\"tbl\");\r\n");
      out.write("\t\t \tvar lastRow = objTable.rows.length+1;\r\n");
      out.write("\t\t \tvar rtnCnt = 0;\r\n");
      out.write("\r\n");
      out.write("\t\t \tfor(var i = lastRow; i > 1; i--){\r\n");
      out.write("\t\t   \t\tif(document.getElementsByTagName(\"TR\")[i].cells[0].firstChild.checked) rtnCnt++;\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t \treturn rtnCnt;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t");
      out.write("\r\n");
      out.write("\t\tfunction goApprovalImplDeptTarget(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar chkCnt = checkCount();\r\n");
      out.write("\t\t    if(chkCnt > 0) {\r\n");
      out.write("\t\t    \tparent.approvalDeptTarget.addApprovalImplDeptMultiRow();\r\n");
      out.write("\t\t \t} else {\r\n");
      out.write("\t\t        alert(\"시행검토자를 선택해주세요.\");\r\n");
      out.write("\t\t        return;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"search_box02\">\r\n");
      out.write("\t\t<form name=\"frm\" id=\"frm\" method=\"post\" action=\"");
      out.print(GROUP_ROOT );
      out.write("/ea/newReport/step2approvalMemberIframe.do\"> \r\n");
      out.write("\t\t<span>사원명</span>\r\n");
      out.write("\t\t<input type=\"text\" name=\"emp_ko_nm\" id=\"emp_ko_nm\" value=\"");
      out.print(emp_ko_nm);
      out.write("\"  class=\"w210\" onKeyPress=\"if(event.keyCode=='13'){goSearch(); return false;}\"/>\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"javascript:goSearch(); return false;\">검색</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"settle_table01\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col style=\"width:28px\" />\r\n");
      out.write("\t\t\t<col style=\"width:85px\" />\r\n");
      out.write("\t\t\t<col style=\"width:80px\" />\r\n");
      out.write("\t\t\t<col style=\"width:70px\" />\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<th>부서</th>\r\n");
      out.write("\t\t\t\t\t<th>직급</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"br_none\">사원명</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"5\" class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"tbl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col style=\"width:28px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col style=\"width:85px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col style=\"width:80px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col style=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(memberList.size()!=0){
									for(int i=0; memberList.size()>i;i++){
									MemberVO memberVO = new MemberVO();
									memberVO = memberList.get(i);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" id=\"emp_no\" name=\"emp_no\" value=\"");
      out.print(memberVO.getEmp_no() );
      out.write('|');
      out.print(StringUtil.nvl(memberVO.getEmp_ko_nm()) );
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"team\">");
      out.print(StringUtil.nvl(memberVO.getDept_ko_nm()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(StringUtil.nvl(memberVO.getGrad_ko_nm()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"br_none\">");
      out.print(StringUtil.nvl(memberVO.getEmp_ko_nm()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								}
								
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"list_btn\">\r\n");
      out.write("\t\t<div class=\"list_button mt5 w265\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"type_01 btn_appr\" onclick=\"javascript:goApprovalImplDeptTarget(); return false;\">시행검토자 추가</button>\t\t\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"type_01 btn_appr\" onclick=\"javascript:goApprovalTarget(); return false;\">결재자 추가</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
