/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-11-09 05:16:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.of.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hanaph.gw.co.common.utils.StringUtil;
import java.util.List;
import java.util.Map;
import com.hanaph.gw.co.code.vo.CodeVO;
import com.hanaph.gw.of.board.vo.BoardVO;
import com.hanaph.gw.pe.member.vo.MemberVO;
import com.hanaph.gw.co.common.utils.StringUtil;
import com.hanaph.gw.co.common.utils.RequestFilterUtil;
import com.hanaph.gw.pe.member.vo.MemberVO;
import javax.servlet.http.HttpSession;
import com.hanaph.gw.pe.member.vo.MemberVO;
import java.util.List;
import com.hanaph.gw.co.menu.vo.MenuVO;
import java.util.ArrayList;
import com.hanaph.gw.co.menu.vo.MenuVO;
import com.hanaph.gw.co.common.utils.StringUtil;
import java.util.List;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1424677116691L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1429838623000L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1418202584955L));
    _jspx_dependants.put("/include/lnb.jsp", Long.valueOf(1444971460463L));
    _jspx_dependants.put("/include/gnb.jsp", Long.valueOf(1444976197526L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1434416046480L));
    _jspx_dependants.put("/common/paging.jsp", Long.valueOf(1418692288909L));
    _jspx_dependants.put("/include/location.jsp", Long.valueOf(1418692302668L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
com.hanaph.gw.co.common.utils.Environment env = new com.hanaph.gw.co.common.utils.Environment();
	
	String HTTPS_GROUP_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_GROUP_ROOT = env.getValue("https.root_dir.url");
	String GROUP_WEB_ROOT = env.getValue("web_root_dir.url");
	String GROUP_ROOT = env.getValue("root_dir.url");
	String JDBC_URL = env.getValue("jdbc.url");
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<BoardVO> boardList = (List<BoardVO>)request.getAttribute("boardList"); //게시판리스트
	List<CodeVO> codeList = (List<CodeVO>)request.getAttribute("codeList"); //게시판종류
	List<MemberVO> authorityMemberList = (List<MemberVO>)request.getAttribute("authorityMemberList"); //삭제권한을 가진 직원
	
	String emp_no = StringUtil.nvl((String)request.getAttribute("emp_no")); //현재 로그인한 직원번호
	String cd = StringUtil.nvl((String)request.getAttribute("cd"),"O01001"); //게시판 종류
	String search_start_ymd = StringUtil.nvl((String)request.getAttribute("search_start_ymd")); //게시시작기간
	String search_end_ymd = StringUtil.nvl((String)request.getAttribute("search_end_ymd")); //게시마지막기간
	String searchType = StringUtil.nvl((String)request.getAttribute("searchType"),"subject"); //검색타입
	String searchKeyword = StringUtil.nvl((String)request.getAttribute("searchKeyword")); //검색키워드
	int totalCnt = (Integer)request.getAttribute("totalCnt"); //게시글 총 카운트
	
	searchKeyword = StringUtil.nvl(RequestFilterUtil.toHtmlTagReplace("", searchKeyword));


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>게시판</title>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>하나제약 그룹웨어</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/dtree.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui-1.10.4.custom.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery.bpopup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/dtree.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/formCheck.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/formCheck.js\" ></script>\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(window).load(function() {\r\n");
      out.write("\t\t$(\"#searchType > option[value=");
      out.print(searchType);
      out.write("]\").attr(\"selected\",\"true\");\r\n");
      out.write("\t\t$(\"#cd > option[value=");
      out.print(cd);
      out.write("]\").attr(\"selected\",\"true\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 검색\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction goSearch(){\r\n");
      out.write("\t\tif(formCheck.containsChars(document.getElementById(\"searchKeyword\").value, \"%\")){\r\n");
      out.write("\t\t\t alert(\"특수문자를 사용할수 없습니다\");\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(formCheck.dateChk($(\"#search_start_ymd\").val(),$(\"#search_end_ymd\").val())<0){\r\n");
      out.write("\t\t\talert(\"공지기간 시작 날짜가 공지기간 종료 날짜 보다 이후 입니다.\");\r\n");
      out.write("\t\t\tstart_ymd.focus();\r\n");
      out.write("\t\t\treturn\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.searchForm.action=\"");
      out.print(GROUP_ROOT);
      out.write("/of/board/boardList.do\";;\r\n");
      out.write("\t\tdocument.searchForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 상세보기 page 이동\r\n");
      out.write("\t * @param seq\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction boardDetail(seq){\r\n");
      out.write("\t\tdocument.frm.seq.value = seq;\r\n");
      out.write("\t\tdocument.frm.action=\"");
      out.print(GROUP_ROOT);
      out.write("/of/board/boardDetail.do\";\r\n");
      out.write("\t\tdocument.frm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 게시판 삭제\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction deleteBoard(){\r\n");
      out.write("\t\tvar seq = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"input[name='delete_seq']:checkbox:checked\").each(function(){\r\n");
      out.write("\t\t\tseq += $(this).val()+\"|\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"input[name='delete_seq']:checkbox:checked\").length < 1){\r\n");
      out.write("\t\t\talert(\"삭제할 대상을 선택해 주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(confirm(\"삭제 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\tdocument.frm.seq.value = seq;\r\n");
      out.write("\t\t\tdocument.frm.action = \"");
      out.print(GROUP_ROOT);
      out.write("/of/board/deleteBoard.do\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 게시판 등록 폼으로 이동\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction insertForm(){\r\n");
      out.write("\t\tdocument.frm.action=\"");
      out.print(GROUP_ROOT);
      out.write("/of/board/insertBoardForm.do\";\r\n");
      out.write("\t\tdocument.frm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 게시글 읽은 임직원 레이어 팝업\r\n");
      out.write("\t * @param board_seq\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction boardReadData(board_seq){\r\n");
      out.write("\t\t$('#boardReadData').bPopup({\r\n");
      out.write("\t\t\tcontent:'iframe', //'ajax', 'iframe' or 'image'\r\n");
      out.write("\t\t\tiframeAttr:'scrolling=\"no\" frameborder=\"0\" width=\"550px\" height=\"295px\"',\r\n");
      out.write("\t\t\tfollow: [true, true],\r\n");
      out.write("\t\t\tcontentContainer:'.board_content',\r\n");
      out.write("\t\t\tmodalClose: true,\r\n");
      out.write("            opacity: 0.6,\r\n");
      out.write("            positionStyle: 'fixed',\r\n");
      out.write("            loadUrl:'");
      out.print(GROUP_ROOT);
      out.write("/of/common/commonReadData.do?seq=' + board_seq + '&type=BOARD',\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 레이어 팝업 닫기\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction layerClose(){ \r\n");
      out.write("\t\t$('#boardReadData').bPopup().close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 체크박스 전체 선택\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction allCheck2(){\r\n");
      out.write("\t\t$(\"input[name=allCheck]:checkbox\").each(function() {\r\n");
      out.write("    \t\tif($(this).is(':checked')) {\r\n");
      out.write("                $(\"input[name=delete_seq]\").prop(\"checked\", true);\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"input[name=delete_seq]\").prop(\"checked\", false);\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

	HttpSession headerSession = request.getSession(false);	
	MemberVO headerMemberVO = (MemberVO) headerSession.getAttribute("gwUser");

      out.write('\r');
      out.write('\n');

	String user_id ="";
	String pass="";

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction logOut(){\r\n");
      out.write("\t\tif(confirm(\"로그아웃 하시겠습니까?\")){\r\n");
      out.write("\t\t\t location.href = \"");
      out.print(GROUP_ROOT);
      out.write("/co/login/logOut.do\";  // 이동할주소\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap_header\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<h1><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/main/main.do'\"><img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/header_logo.jpg\" alt=\"하나제약 그룹웨어\" /></a></h1>\r\n");
      out.write("\t\t<div class=\"wrap_menu\">\r\n");
      out.write("\t\t\t<span class=\"connect\">");
      out.print(headerMemberVO.getEmp_ko_nm() );
      out.write("</span>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li class=\"first\"><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/pe/member/memberDetail.do'\">내정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"javascript:Commons.popupOpen('passChg', '");
      out.print(GROUP_ROOT);
      out.write("/co/login/passwordChangeForm.do', '290', '239'); return false;\">비밀번호변경</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"javascript:logOut(); return false;\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/of/notice/noticeList.do?search_start_ymd=2015-01-01&search_read_yn=N'\">공지 ");
      out.print(headerMemberVO.getNoticeCountNoread() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/of/message/messageList.do?start_ymd=2015-01-01&type=1&search_read_yn=N'\">받은쪽지 ");
      out.print(headerMemberVO.getMessageReceiveCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/receive/receiveList.do?search_start_ymd=2015-01-01&search_appr_state=E03001'\">문서결재 ");
      out.print(headerMemberVO.getReceiveCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/implement/implementList.do?search_start_dt=2015-01-01&approval_type=E03001&search_read_yn=N'\">시행결재중 ");
      out.print(headerMemberVO.getImplementOngoingCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/implement/implementList.do?search_start_dt=2015-01-01&approval_type=E03002&search_read_yn=N'\">시행완료 ");
      out.print(headerMemberVO.getImplementCompleteCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- 20150609 웹메일 클릭 시 로그인 되지 않도록 수정 -->\r\n");
      out.write("\t\t\t<!-- 원복 시 해당 주석 삭제 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"http://gwmail.hanaph.co.kr/index.php?_user=");
      out.print(headerMemberVO.getE_mail() );
      out.write("\" target=\"_blank\" class=\"webmail\" >WEB MAIL</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<MenuVO> gnbMenuList = (List)headerSession.getAttribute("gwGNB"); 

      out.write("\r\n");
      out.write("<div class=\"wrap_gnb\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");

		if(gnbMenuList.size() > 0){
			for(int i=0; gnbMenuList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = gnbMenuList.get(i);
		
      out.write("\r\n");
      out.write("\t\t<li ");
if(i == 0){ 
      out.write("class=\"first\"");
} 
      out.write("><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(menuVO.getMenu_nm() );
 if("jdbc:oracle:thin:@58.229.234.12:1521:ORCL".equals(JDBC_URL)){ 
      out.write('(');
      out.write('테');
      out.write(')');
} 
      out.write("</a></li>\r\n");
      out.write("\t\t");
	}
		} 
      out.write(" \r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<div class=\"wrap_con\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<MenuVO> lnbMentList = (List<MenuVO>)request.getAttribute("lnbMenuList");
	if(lnbMentList == null){
		lnbMentList = new ArrayList();
	}
	String MENU_CHILD = com.hanaph.gw.co.common.utils.StringUtil.nvl((String)request.getAttribute("MENU_CHILD"), "01");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"location\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/main/main.do'\"><img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/location_icon_home.gif\" alt=\"home\" /></a> > </li>\r\n");
      out.write("\t\t");

		if(lnbMentList.size()!=0){
			
			for(int i=0; lnbMentList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = lnbMentList.get(i);
				if(menuVO.getMenu_child().equals(MENU_CHILD)){
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"#\">");
      out.print(menuVO.getParents_menu_nm() );
      out.write("</a> > </li>\r\n");
      out.write("\t\t<li><a href=\"");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl() );
      out.write("\" class=\"active\">");
      out.print(menuVO.getMenu_nm() );
      out.write("</a></li>\r\n");
      out.write("\t\t");

				}
			}
		}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div class=\"lnb\">\r\n");
      out.write("\t");

		if(lnbMentList.size()!=0){
			MenuVO menuVO = new MenuVO();
			menuVO = lnbMentList.get(0);
	
      out.write("\r\n");
      out.write("\t<p class=\"tit\">");
      out.print(StringUtil.nvl(menuVO.getParents_menu_nm()) );
      out.write("</p>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");

		if(lnbMentList.size()!=0){
			for(int i=0; lnbMentList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = lnbMentList.get(i);
		
      out.write("\r\n");
      out.write("\t\t<li ");
if(i==lnbMentList.size()-1){ 
      out.write(" class=\"last\"");
} 
      out.write(">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t");
if(menuVO.getMenu_child().length() == 6) {
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;ㄴ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print(StringUtil.nvl(menuVO.getMenu_nm()));
      out.write("\t\r\n");
      out.write("\t\t\t\t<span class=\"none_check\">&nbsp;");
      out.print(StringUtil.nvl(menuVO.getAdd_menu_nm()));
      out.write("</span>\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"cont float_left\">\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t");

					if(codeList.size()!=0){
							for(int i=0;i<codeList.size();i++){
								CodeVO codeVO = new CodeVO();
								codeVO = codeList.get(i);
								if(cd.equals(codeVO.getCd())){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(codeVO.getCd_nm());
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
							}
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<div class=\"noticeboard_box\">\r\n");
      out.write("\t\t\t\t\t<form id=\"searchForm\" name=\"searchForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"serch_box\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"serch_con01\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sc_txt\">게시기간</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"serch_date_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"serch_date\" name=\"search_start_ymd\" id=\"search_start_ymd\" value=\"");
      out.print(search_start_ymd);
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">날짜선택</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> ~ \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"serch_date_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"serch_date\" name=\"search_end_ymd\" id=\"search_end_ymd\" value=\"");
      out.print(search_end_ymd);
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">날짜선택</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sc_txt\">게시판종류</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"serch_select01\" id=\"cd\" name=\"cd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(codeList.size()!=0){
									for(int i=0;i<codeList.size();i++){
										CodeVO codeVO = new CodeVO();
										codeVO = codeList.get(i);
										if("Y".equals(codeVO.getUse_yn())){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(codeVO.getCd());
      out.write('"');
      out.write(' ');
      out.print(cd.equals(codeVO.getCd())? "selected": "");
      out.write(' ');
      out.write(' ');
      out.write('>');
      out.print(codeVO.getCd_nm());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

										}
									}
								}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"cont02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sc_txt\">게시물 검색</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"serch_select02\" id=\"searchType\" name=\"searchType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"subject\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"create_no\">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"serch_txt\" id=\"searchKeyword\" value=\"");
      out.print(searchKeyword);
      out.write("\" maxlength=\"32\" name=\"searchKeyword\" value=\"");
      out.print(searchKeyword);
      out.write("\" onKeyPress=\"if(event.keyCode=='13'){goSearch(); return false;}\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"serch_btn\" onclick=\"javascript:goSearch();\"><button type=\"button\">검색</button></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div class=\"list_btn\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list_button\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"type_01\" onclick=\"javascript:insertForm();\">신규</button>\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(authorityMemberList != null){
								for(int i=0; authorityMemberList.size()>i;i++){
									MemberVO memberVO = new MemberVO();
									memberVO = authorityMemberList.get(i);
									if(emp_no.equals(memberVO.getEmp_no())){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"type_01\" onclick=\"javascript:deleteBoard();\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t");

									}
								}
							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"list_t\">* 안 읽은 글은 제목이 <span class=\"none_check\">파란색</span>으로 표시됩니다.</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cont_box cont_table05\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"frm\" name=\"frm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"search_start_ymd\" name=\"search_start_ymd\" value=\"");
      out.print(search_start_ymd );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"search_end_ymd\" name=\"search_end_ymd\" value=\"");
      out.print(search_end_ymd );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"searchType\" name=\"searchType\" value=\"");
      out.print(searchType );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"searchKeyword\" name=\"searchKeyword\" value=\"");
      out.print(searchKeyword );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"cd\" name=\"cd\" value=\"");
      out.print(cd );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"seq\" name=\"seq\" />\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"5%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"50%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"8%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"7%\" />\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"allCheck\" name=\"allCheck\" onclick=\"javascript:allCheck2();\"/></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>제목(댓글수)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>게시일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>게시자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>읽은수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th class=\"br_none\">첨부</th>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if(boardList.size()!=0){
											for(int i=0; boardList.size()>i;i++){
												BoardVO boardVO = new BoardVO();
												boardVO=boardList.get(i);
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete_seq\" id=\"delete_seq\" value=\"");
      out.print(boardVO.getSeq());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td onclick=\"javascript:boardDetail('");
      out.print(boardVO.getSeq());
      out.write("')\" class=\"list_txt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div ");
if(!"Y".equals(boardVO.getRead_yn())){
      out.write("class=\"none_check\"");
}
      out.write(" style=\"word-wrap:break-word; white-space:normal; display:inline-block; width:350px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(StringUtil.nvl(RequestFilterUtil.toHtmlTagReplace("", boardVO.getSubject())) );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"count\">(");
      out.print(StringUtil.nvl(boardVO.getComment_cnt(),"0"));
      out.write(")</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(boardVO.getCreate_dt());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td onclick=\"javascript:Commons.memberPopup('");
      out.print(boardVO.getCreate_no());
      out.write("');\">");
      out.print(boardVO.getEmp_ko_nm());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td onclick=\"javascript:boardReadData('");
      out.print(boardVO.getSeq());
      out.write("')\">");
      out.print(boardVO.getRead_cnt());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"br_none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if(boardVO.getAttach_cnt() > 0){
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/img_file.png\" alt=\"파일첨부\" /></td>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											}
									}else{
										
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><td class=\"br_none\" colspan=\"6\">게시물이 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"paging\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrap_total\">\r\n");
      out.write("\t\t\t\t\t\t\t* 총 건수 : <span class=\"cnt\">");
      out.print(StringUtil.makeMoneyType(totalCnt));
      out.write("</span>건\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wrap_paging\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write('\r');
      out.write('\n');

	String pagingStr = com.hanaph.gw.co.common.utils.StringUtil.nvl((String)request.getAttribute("pagingStr"),"");
	String currentPage = com.hanaph.gw.co.common.utils.StringUtil.nvl(request.getParameter("currentPage"),"1");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar $form = $(\"#frm\");\r\n");
      out.write("\tif($form.length > 0) {\r\n");
      out.write("\t//\t\t \t/* 정보 세팅 */\r\n");
      out.write("\t\t$(\"<input></input>\").attr({type:\"hidden\", name:\"currentPage\",id:\"currentPage\", value:$.trim('");
      out.print(currentPage);
      out.write("')}).appendTo($form);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goPage(v_curr_page) \r\n");
      out.write("\t{\r\n");
      out.write("\t    $(\"#currentPage\").val(v_curr_page);\r\n");
      out.write("\t    $form.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
if(!"".equals(pagingStr) && !"".equals(currentPage)){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(pagingStr);
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='boardReadData' style='display:none; width:auto; height:auto; '>\r\n");
      out.write("\t\t<div class='board_content'></div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap_foot\">\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\tCopyright ⓒ 2014 <span class=\"copy_fc\">HANA PHARM CO.</span>, LTD. All Right Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
