CREATE OR REPLACE PROCEDURE USRBM.SP_CRT_EVENT_7EX
 IS

P_CUR_DATE VARCHAR2(8);

BEGIN             

    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')
    INTO     P_CUR_DATE
    FROM    DUAL;

SP_LOG('SP_CRT_EVENT_7EX.....................P_CUR_DATE['||P_CUR_DATE||']');
    
    --    SP_CRT_EVENT_7EX309(P_CUR_DATE);
   --        SP_CRT_EVENT_7EX410(P_CUR_DATE);
        --SP_CRT_EVENT_7EX612(P_CUR_DATE); 
        
        SP_CRT_EVENT_7EX611(P_CUR_DATE);
/*
    IF RACE_TERM = '309' THEN
        SP_CRT_EVENT_7EX309(P_CUR_DATE);
    ELSIF RACE_TERM = '410' THEN
        SP_CRT_EVENT_7EX410(P_CUR_DATE);
    ELSIF RACE_TERM = '511' THEN
        SP_CRT_EVENT_7EX511(P_CUR_DATE);
    END IF;
*/    
    COMMIT;
                
END;
/
