/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-04-28 08:15:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.business;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hanaph.saleon.member.vo.LoginUserVO;
import com.hanaph.saleon.common.utils.StringUtil;
import com.hanaph.saleon.common.utils.WebUtil;
import com.hanaph.saleon.business.vo.BusinessVO;

public final class customerLedgerList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1430124365934L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/sessionCheck.jsp", Long.valueOf(1430193978042L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LoginUserVO loginUserVO = (LoginUserVO) session.getAttribute("onlineUser");	//세션생성 세션에서 emp_code를 가져온다.
	
	String userEmpCode  = "";		// 사원 코드
	String userEmpName  = "";		// 사원 이름
	String userEmpGb    = "";		// 사원 구분 
	String userDeptCode = "";		// 부서코드
	String userDeptName = "";		// 부서명
	String userGradeName = "";		// 사원 Grade Name
	String userDeptCd = "";			//hanahr 부서정보
	String userAssgnCd = "";			//직책 코드
	String userAssgnName = "";			//직책 코드명
	/*
	 * 로그인 정보가 있는경우
	 */
	if(loginUserVO != null){
		userEmpCode = StringUtil.nvl(loginUserVO.getEmp_code());    	// 사용자코드
		userEmpName = StringUtil.nvl(loginUserVO.getEmp_name());		// 사용자명
		userEmpGb = StringUtil.nvl(loginUserVO.getEmp_gb());			// 사용자 구분 코드
		userDeptCode = StringUtil.nvl(loginUserVO.getDept_code());  	// 부서 코드
		userDeptName = StringUtil.nvl(loginUserVO.getDept_name());		// 부서 명
		userGradeName = StringUtil.nvl(loginUserVO.getGrade_name());	// 사용자 부서명
		userDeptCd = StringUtil.nvl(loginUserVO.getDept_cd());  	    // 부서 코드
		userAssgnCd = StringUtil.nvl(loginUserVO.getAssgn_cd());  	    // 직책 코드
		userAssgnName = StringUtil.nvl(loginUserVO.getAssgn_name());  	// 직책 코드명
	}
	
	/* 현재 URI에 해당하는 프로그램 No(pgm_no) */
	String currPgmNoByUri = request.getAttribute("pgm_no") == null ? "" : (String) request.getAttribute("pgm_no");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	com.hanaph.saleon.common.utils.Environment env = new com.hanaph.saleon.common.utils.Environment();	//환경 변수
	
	String HTTPS_ONLINE_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_ONLINE_ROOT = env.getValue("https.root_dir.url");
	String ONLINE_WEB_ROOT = env.getValue("web_root_dir.url");		//URL 프로토콜, 도메인, 포트, 서브컨텍스트명, web디렉토리
	String ONLINE_ROOT = env.getValue("root_dir.url");				//URL 프로토콜, 도메인, 포트, 서브컨텍스트명
	String JDBC_URL = env.getValue("jdbc.url");
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	/* 사용자 정보 셋팅(부서코드, pda 권한) */
	BusinessVO commonEmpInfo = new BusinessVO();
	commonEmpInfo = (BusinessVO)request.getAttribute("commonEmpInfo");
	
	boolean isNull = true; // null flag
	String dept_cd = ""; // 부서코드
	String pda_auth = ""; // pda 권한
	
	if(null != commonEmpInfo) { // null이 아닐 경우
		dept_cd = commonEmpInfo.getDept_cd();
		pda_auth = commonEmpInfo.getPda_auth();
		isNull = false;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar ONLINE_ROOT = \"");
      out.print(ONLINE_ROOT );
      out.write("\";\t\t/*환경변수*/\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/placeholders.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/easyui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/jquery-ui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui.theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/gw_sample.css\">");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/ui.jqgrid.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/grid.locale-kr.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/formCheck.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/business.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar customerLedgerActionFlag = false; // 거래처원장조회 부가기능(인쇄, 엑셀다운로드) 사용 가능 여부 flag\r\n");
      out.write("\tvar indirectLedgerActionFlag = false; // 간납처원장조회 부가기능(인쇄, 엑셀다운로드) 사용 가능 여부 flag\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 사원 정보 존재 여부 */\r\n");
      out.write("\t\tif (");
      out.print(isNull);
      out.write(") {\r\n");
      out.write("\t\t\talert(\"사원정보 자료가 없습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* jqGrid의 jsonReader 옵션 전역 설정. row 반복 형태의 json 처리.  */\r\n");
      out.write("\t    jsonReader : {\r\n");
      out.write("            repeatitems: false;\r\n");
      out.write("    \t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t/* 거래처 원장 목록 grid*/\r\n");
      out.write("\t\t$(\"#grid_list_customerLedger\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"일자\",\"납품처\", \"품목\", \"단위\", \"수량\", \"단가\", \"공급가액\", \"세액\", \"합계금액\", \"수금\", \"잔액\", \"매출할인\", \"비고\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"ymd\",\t\tindex:\"ymd\", \t\talign:\"center\", width:80},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_nm\",\tindex:\"rcust_nm\", \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"item_nm\",\tindex:\"item_nm\", \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"standard\",\tindex:\"standard\", \talign:\"left\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"qty\",\t\tindex:\"qty\", \t\talign:\"right\", width:50,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"danga\",\t\tindex:\"danga\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"amt\",\t\tindex:\"amt\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"vat\",\t\tindex:\"vat\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"tot\",\t\tindex:\"tot\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"sukum\",\t\tindex:\"sukum\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rem_amt\",\tindex:\"rem_amt\", \talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dc_amt\",\t\tindex:\"dc_amt\", \talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"bigo\",\t\tindex:\"bigo\", \t\talign:\"left\", width:200}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40,50],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 1 row 생성 될 때 마다 호출 */\r\n");
      out.write("\t\t\tafterInsertRow:function(rowid, rowdata , rowelem){\r\n");
      out.write("\t\t\t\t$(\"#grid_list_customerLedger\").jqGrid(\"setCell\",rowid,\"rem_amt\",\"\",{color:\"#0000FF\"});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page==1){\r\n");
      out.write("\t\t\t\t\t\tvar datarow = {\r\n");
      out.write("\t\t\t\t\t\t\tymd : \"\",\r\n");
      out.write("\t\t\t\t\t\t\trcust_nm : \"\",\r\n");
      out.write("\t\t\t\t\t\t\titem_nm : \"[ 이월잔액 ]\",\r\n");
      out.write("\t\t\t\t\t\t\tstandard : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tqty : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tdanga : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tamt : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tvat : \"\",\r\n");
      out.write("\t\t\t\t\t\t\ttot : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tsukum : \"\",\r\n");
      out.write("\t\t\t\t\t\t\trem_amt : data.rows[0].before_amt,\r\n");
      out.write("\t\t\t\t\t\t\tdc_amt : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tbigo : \"\"\r\n");
      out.write("\t\t\t\t\t\t}; // 이월잔액 정보\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_customerLedger\").addRowData(0,datarow,\"first\"); // list 맨 처음에 넣어준다.\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/* 합계정보 */\r\n");
      out.write("\t\t\t\t\tvar amt = data.totalCountInfo.total_amt;\r\n");
      out.write("\t\t\t\t\tvar vat = data.totalCountInfo.total_vat;\r\n");
      out.write("\t\t\t\t\tvar tot = Number(amt) + Number(vat);\r\n");
      out.write("\t\t\t\t\tvar sukum = data.totalCountInfo.total_sukum;\r\n");
      out.write("\t\t\t\t\tvar dc_amt = data.totalCountInfo.total_dc_amt;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#customer_amt\").val(Commons.addComma(amt)); // 공급가액\r\n");
      out.write("\t\t\t\t\t$(\"#customer_vat\").val(Commons.addComma(vat)); // 세액\r\n");
      out.write("\t\t\t\t\t$(\"#customer_tot\").val(Commons.addComma(tot)); // 공급총액\r\n");
      out.write("\t\t\t\t\t$(\"#customer_sukum\").val(Commons.addComma(sukum)); // 수금액\r\n");
      out.write("\t\t\t\t\t$(\"#customer_dc_amt\").val(Commons.addComma(dc_amt)); // 할인액\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcustomerLedgerActionFlag = true; // 인쇄, 엑셀 사용 가능하도록\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\tcustomerLedgerActionFlag = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_customerLedger\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 간납처 원장 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_indirectLedger\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"일자\",\"거래처\", \"품목\", \"단위\", \"수량\", \"단가\", \"공급가액\", \"세액\", \"합계금액\", \"수금\", \"잔액\", \"매출할인\", \"비고\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"ymd\",\t\tindex:\"ymd\", \t\talign:\"center\", width:80},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_nm\",\tindex:\"rcust_nm\", \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"item_nm\",\tindex:\"item_nm\", \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"standard\",\tindex:\"standard\", \talign:\"left\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"qty\",\t\tindex:\"qty\", \t\talign:\"right\", width:50,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"danga\",\t\tindex:\"danga\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"amt\",\t\tindex:\"amt\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"vat\",\t\tindex:\"vat\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"tot\",\t\tindex:\"tot\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"sukum\",\t\tindex:\"sukum\", \t\talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rem_amt\",\tindex:\"rem_amt\", \talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dc_amt\",\t\tindex:\"dc_amt\", \talign:\"right\", width:100,\tformatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"bigo\",\t\tindex:\"bigo\", \t\talign:\"left\", width:200}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40,50],\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* 1 row 생성 될 때 마다 호출 */\r\n");
      out.write("\t\t\tafterInsertRow:function(rowid, rowdata , rowelem){\r\n");
      out.write("\t\t\t\t$(\"#grid_list_indirectLedger\").jqGrid(\"setCell\",rowid,\"rem_amt\",\"\",{color:\"#0000FF\"});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page==1){\r\n");
      out.write("\t\t\t\t\t\tvar datarow = {\r\n");
      out.write("\t\t\t\t\t\t\tymd : \"\",\r\n");
      out.write("\t\t\t\t\t\t\trcust_nm : \"\",\r\n");
      out.write("\t\t\t\t\t\t\titem_nm : \"[ 이월잔액 ]\",\r\n");
      out.write("\t\t\t\t\t\t\tstandard : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tqty : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tdanga : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tamt : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tvat : \"\",\r\n");
      out.write("\t\t\t\t\t\t\ttot : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tsukum : \"\",\r\n");
      out.write("\t\t\t\t\t\t\trem_amt : data.rows[0].before_amt,\r\n");
      out.write("\t\t\t\t\t\t\tdc_amt : \"\",\r\n");
      out.write("\t\t\t\t\t\t\tbigo : \"\"\r\n");
      out.write("\t\t\t\t\t\t}; // 이월잔액 정보\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_indirectLedger\").addRowData(0,datarow,\"first\");  // list 맨 처음에 넣어준다.\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/* 합계정보 */\r\n");
      out.write("\t\t\t\t\tvar amt = data.totalCountInfo.total_amt;\r\n");
      out.write("\t\t\t\t\tvar vat = data.totalCountInfo.total_vat;\r\n");
      out.write("\t\t\t\t\tvar tot = Number(amt) + Number(vat);\r\n");
      out.write("\t\t\t\t\tvar sukum = data.totalCountInfo.total_sukum;\r\n");
      out.write("\t\t\t\t\tvar dc_amt = data.totalCountInfo.total_dc_amt;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#indirect_amt\").val(Commons.addComma(amt)); // 공급가액\r\n");
      out.write("\t\t\t\t\t$(\"#indirect_vat\").val(Commons.addComma(vat)); // 세액\r\n");
      out.write("\t\t\t\t\t$(\"#indirect_tot\").val(Commons.addComma(tot)); // 공급총액\r\n");
      out.write("\t\t\t\t\t$(\"#indirect_sukum\").val(Commons.addComma(sukum)); // 수금액\r\n");
      out.write("\t\t\t\t\t$(\"#indirect_dc_amt\").val(Commons.addComma(dc_amt)); // 할인액\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tindirectLedgerActionFlag = true; // 인쇄, 엑셀 사용 가능하도록\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\tindirectLedgerActionFlag = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_indirectLedger\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t/* 거래처 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_customer\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"거래처코드\",\"거래처명\",\"부서명\",\"사원명\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_id\",\tindex:\"cust_id\", \talign:\"center\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_nm\",\tindex:\"cust_nm\", \talign:\"left\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dept_nm\",\tindex:\"dept_nm\", \talign:\"left\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"sawon_nm\",\tindex:\"sawon_nm\", \talign:\"center\"}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40],\r\n");
      out.write("\t\t\tautowidth:true,\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_customer\").setSelection(1, true); // 첫번째 row 선택\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#grid_list_customerLedger\").jqGrid(\"clearGridData\"); // 거래처원장목록 grid 영역 초기화\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* row 선택 시 */\r\n");
      out.write("\t\t\tonSelectRow: function(){\r\n");
      out.write("\t\t\t\tvar id = $(\"#grid_list_customer\").jqGrid('getGridParam','selrow'); // 현재 선택한 row의 id\r\n");
      out.write("\t\t\t\tvar ret = $(\"#grid_list_customer\").jqGrid('getRowData',id); // 해당 id를 갖고 있는 row의 정보\r\n");
      out.write("\t\t\t\tgetCustomerLedgerGridList(ret.cust_id); // 거래처원장목록 조회\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_customer\"\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 간납처 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_indirect\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"간납처코드\",\"거래처명\",\"부서명\",\"사원명\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_id\",\tindex:\"cust_id\", \talign:\"center\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_nm\",\tindex:\"cust_nm\", \talign:\"left\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dept_nm\",\tindex:\"dept_nm\", \talign:\"left\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"sawon_nm\",\tindex:\"sawon_nm\", \talign:\"center\"}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40],\r\n");
      out.write("\t\t\tautowidth:true,\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_indirect\").setSelection(1, true); // 첫번째 row 선택\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#grid_list_indirectLedger\").jqGrid(\"clearGridData\"); // 간납처원장목록 grid 영역 초기화\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* row 선택 시 */\r\n");
      out.write("\t\t\tonSelectRow: function(){\r\n");
      out.write("\t\t\t\tvar id = $(\"#grid_list_indirect\").jqGrid('getGridParam','selrow'); // 현재 선택한 row의 id\r\n");
      out.write("\t\t\t\tvar ret = $(\"#grid_list_indirect\").jqGrid('getRowData',id); // 해당 id를 갖고 있는 row의 정보\r\n");
      out.write("\t\t\t\tgetCustomerLedgerGridList(ret.cust_id); // 간납처원장목록 조회\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_indirect\"\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 조회 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#ct_retrieve_btn_type02\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgetCustomerGridList();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 인쇄 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_print\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgoExtraAction('print');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 엑셀 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_excel\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgoExtraAction('excel');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 닫기 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_close\").on(\"click\",function(){\r\n");
      out.write("\t\t\tparent.Commons.closeTab('거래처원장조회');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 조회일자 셋팅(이번 달 1일 ~ 오늘) */\r\n");
      out.write("\t\tCommons.setDate(\"ad_fr_date\", \"ad_to_date\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* grid 영역 넓이 셋팅 */\r\n");
      out.write("\t\t$(\"#grid_list_customer\").setGridWidth($(\"#customerLedger\").width() , true);\r\n");
      out.write("\t\t$(\"#grid_list_indirect\").setGridWidth($(\"#customerLedger\").width() , true);\r\n");
      out.write("\t\t$(\"#grid_list_customerLedger\").setGridWidth($(\"#customerLedger\").width() , false);\r\n");
      out.write("\t\t$(\"#grid_list_indirectLedger\").setGridWidth($(\"#customerLedger\").width() , false);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 엔터키 눌렸을 경우 조회되도록. */\r\n");
      out.write("\t\t$(\"body\").on(\"keydown\", function(event){\r\n");
      out.write("\t\t\tif($(\"#ct_retrieve_btn_type02\").prop('disabled') == false){\r\n");
      out.write("\t\t\t\tif(event.keyCode==13 && event.target.name!=\"grid_count\"){\r\n");
      out.write("\t\t\t\t\tgetCustomerGridList();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 브라우저 창의 사이즈가 변경될 때 */\r\n");
      out.write("\t$(window).resize(function(){\r\n");
      out.write("\t\t$(\"#grid_list_customer\").setGridWidth($(\"#customerLedger\").width() , true);\r\n");
      out.write("\t\t$(\"#grid_list_indirect\").setGridWidth($(\"#customerLedger\").width() , true);\r\n");
      out.write("\t\t$(\"#grid_list_customerLedger\").setGridWidth($(\"#customerLedger\").width() , false);\r\n");
      out.write("\t\t$(\"#grid_list_indirectLedger\").setGridWidth($(\"#customerLedger\").width() , false);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 거래처, 간납처 목록조회 */\r\n");
      out.write("\tfunction getCustomerGridList(){\r\n");
      out.write("\t\tvar selectType = $(\"#selectType option:selected\").val();\r\n");
      out.write("\t\tvar ad_fr_date = $(\"#ad_fr_date\").val();\r\n");
      out.write("\t\tvar ad_to_date = $(\"#ad_to_date\").val();\r\n");
      out.write("\t\tvar as_fr_cust = $(\"#as_fr_cust\").val();\r\n");
      out.write("\t\tvar as_to_cust = $(\"#as_to_cust\").val();\r\n");
      out.write("\t\tvar as_dept_cd = $(\"#as_dept_cd\").val();\r\n");
      out.write("\t\tvar as_pda_auth = $(\"#as_pda_auth\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 유효성 체크 */\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(ad_fr_date)) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#ad_fr_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(ad_to_date)) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#ad_to_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (formCheck.dateChk(ad_fr_date, ad_to_date) < 0) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 확인하세요!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 파라미터 셋팅 */\r\n");
      out.write("\t\tvar params = {\r\n");
      out.write("\t\t\tselectType : selectType,\r\n");
      out.write("\t\t\tad_fr_date : ad_fr_date,\r\n");
      out.write("\t\t\tad_to_date : ad_to_date,\r\n");
      out.write("\t\t\tas_fr_cust : as_fr_cust,\r\n");
      out.write("\t\t\tas_to_cust : as_to_cust,\r\n");
      out.write("\t\t\tas_dept_cd : as_dept_cd,\r\n");
      out.write("\t\t\tas_pda_auth : as_pda_auth\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar paramStr = $.param(params);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 호출 */\r\n");
      out.write("\t\t$(\"#grid_list_\" + selectType).jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/customerGridList.do?\" + paramStr}).trigger(\"reloadGrid\", [{page:1}]);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 거래처, 간납처 원장목록조회 */\r\n");
      out.write("\tfunction getCustomerLedgerGridList(cust_id){\r\n");
      out.write("\t\tvar selectType = $(\"#selectType option:selected\").val();\r\n");
      out.write("\t\tvar ad_fr_date = $(\"#ad_fr_date\").val();\r\n");
      out.write("\t\tvar ad_to_date = $(\"#ad_to_date\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 엑셀 다운로드 용 인자 셋팅 */\r\n");
      out.write("\t\t$(\"#as_cust_id_\" + selectType).val(cust_id);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 유효성 체크 */\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(ad_fr_date)) {\r\n");
      out.write("\t\t\talert(\"올바른 조회 기간을 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#ad_fr_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(ad_to_date)) {\r\n");
      out.write("\t\t\talert(\"올바른 조회 기간을 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#ad_to_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (formCheck.dateChk(ad_fr_date, ad_to_date) < 0) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 확인하세요!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 파라미터 셋팅 */\r\n");
      out.write("\t\tvar params = {\r\n");
      out.write("\t\t\tselectType : selectType,\r\n");
      out.write("\t\t\tad_fr_date : ad_fr_date,\r\n");
      out.write("\t\t\tad_to_date : ad_to_date,\r\n");
      out.write("\t\t\tas_cust_id : cust_id\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar paramStr = $.param(params);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 호출 */\r\n");
      out.write("\t\t$(\"#grid_list_\" + selectType + \"Ledger\").jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/customerLedgerGridList.do?\" + paramStr}).trigger(\"reloadGrid\", [{page:1}]);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 금액 커스텀 포맷 */\r\n");
      out.write("\tfunction amountFormatter(cellvalue){\r\n");
      out.write("\t\tvar returnValue = \"\";\r\n");
      out.write("\t\tif (\"0\" != cellvalue && \"\" != cellvalue) {\r\n");
      out.write("\t\t\treturnValue = Math.round(cellvalue);\r\n");
      out.write("\t\t\treturnValue = Commons.addComma(returnValue);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn returnValue.toString();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 조회유형에 따른 grid 영역 교체 */\r\n");
      out.write("\tfunction changeType(value) {\r\n");
      out.write("\t\t$(\".gridArea\").hide();\r\n");
      out.write("\t\t$(\"#\" + value + \"Ledger\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!formCheck.isEmpty($(\"#as_fr_cust\").val())) {\r\n");
      out.write("\t\t\tgetCustomerGridList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 인쇄, 엑셀 실행 */\r\n");
      out.write("\tfunction goExtraAction(type) {\r\n");
      out.write("\t\tvar selectType = $(\"#selectType option:selected\").val()\r\n");
      out.write("\t\tvar selectFlag = false;\r\n");
      out.write("\t\tvar url = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 현재 선택한 조회타입에 따라 실행 가능 여부 셋팅 */\r\n");
      out.write("\t\tif (\"customer\" == selectType) {\r\n");
      out.write("\t\t\tselectFlag = customerLedgerActionFlag; \r\n");
      out.write("\t\t} else if (\"indirect\" == selectType) {\r\n");
      out.write("\t\t\tselectFlag = indirectLedgerActionFlag;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 현재 선택한 기능에 따라 대상 url 셋팅 */\r\n");
      out.write("\t\tif (\"print\" == type) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar id = $(\"#grid_list_\"+selectType).jqGrid('getGridParam','selrow'); // 현재 선택한 row의 id\r\n");
      out.write("\t\t\tvar ret = $(\"#grid_list_\"+selectType).jqGrid('getRowData',id); // 해당 id를 갖고 있는 row의 정보\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ad_fr_date = $(\"#ad_fr_date\").val();\r\n");
      out.write("\t\t\tvar ad_to_date = $(\"#ad_to_date\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar param = \"ad_fr_date=\" + ad_fr_date + \"&ad_to_date=\" + ad_to_date + \"&selectType=\" + selectType + \"&as_cust_id=\" + ret.cust_id;\t// 파라미터 셋팅\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\turl = \"");
      out.print(ONLINE_ROOT);
      out.write("/business/ledgerListPrintPopup.do?\" + param;\r\n");
      out.write("\t\t} else if (\"excel\" == type) {\r\n");
      out.write("\t\t\turl = \"");
      out.print(ONLINE_ROOT);
      out.write("/business/ledgerGridListExcelDown.do\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tCommons.extraAction(selectFlag, type, url, selectType);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<form name=\"frm\" id=\"frm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_cust_id_customer\" id=\"as_cust_id_customer\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_cust_id_indirect\" id=\"as_cust_id_indirect\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_dept_cd\" id=\"as_dept_cd\" value=\"");
      out.print(dept_cd );
      out.write("\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_pda_auth\" id=\"as_pda_auth\" value=\"");
      out.print(pda_auth );
      out.write("\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"wrap_search\">\r\n");
      out.write("\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t<div class=\"float_l\">\r\n");
      out.write("\t\t\t\t\t<label class=\"w70\">주문일</label>\r\n");
      out.write("\t\t\t\t\t<p class=\"wrap_date\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" id=\"ad_fr_date\" name=\"ad_fr_date\" />\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">달력보기</span></button>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t~\r\n");
      out.write("\t\t\t\t\t<p class=\"wrap_date\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" id=\"ad_to_date\" name=\"ad_to_date\" />\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">달력보기</span></button>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">구분</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"selectType\" class=\"w100\" name=\"selectType\" onchange=\"javascript:changeType(this.value);\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"customer\">거래처</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"indirect\">간납처</option>\r\n");
      out.write("\t\t\t\t\t</select><br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label class=\"w70\">거래처</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" maxlength=\"10\" class=\"w140\" id=\"as_fr_cust\" name=\"as_fr_cust\" onblur=\"javascript:Business.getCustomerName(this.id);\"/>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_search\" onclick=\"javascript:Commons.popupOpen('as_fr_cust', '");
      out.print(ONLINE_ROOT);
      out.write("/business/common/customerList.do', '600', '655');\" ><span class=\"blind\">찾기</span></button>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"w230 ipt_disable\" id=\"as_fr_cust_name\" name=\"as_fr_cust_name\" readonly />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"wrap_search_btn\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "ct_"));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"wrap_btn_group\">\r\n");
      out.write("\t\t\t<div class=\"btn_group ta_r\">\r\n");
      out.write("\t\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "p_"));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"inner_cont2\">\r\n");
      out.write("\t\t\t<div class=\"wrap_result_group gridArea\" id=\"customerLedger\" style=\"display:block;\">\r\n");
      out.write("\t\t\t\t<!-- 거래처 목록 -->\r\n");
      out.write("\t\t\t\t<div class=\"customerLedger\" style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t<table id=\"grid_list_customer\"></table>\r\n");
      out.write("\t\t\t\t\t<div id=\"grid_Pager_customer\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 거래처 원장 목록 -->\r\n");
      out.write("\t\t\t\t<table id=\"grid_list_customerLedger\"></table>\r\n");
      out.write("\t\t\t\t<div id=\"grid_Pager_customerLedger\" class=\"customerLedger\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"wrap_result_group customerLedger\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"float_r\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point\">공급가액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"customer_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">세액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"customer_vat\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">공급총액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"customer_tot\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">수금액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"customer_sukum\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">할인액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"customer_dc_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"wrap_result_group gridArea\" id=\"indirectLedger\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t<!-- 간납처 목록 -->\r\n");
      out.write("\t\t\t\t<div class=\"indirectLedger\" style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t<table id=\"grid_list_indirect\"></table>\r\n");
      out.write("\t\t\t\t\t<div id=\"grid_Pager_indirect\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 간납처 원장 목록 -->\r\n");
      out.write("\t\t\t\t<table id=\"grid_list_indirectLedger\"></table>\r\n");
      out.write("\t\t\t\t<div id=\"grid_Pager_indirectLedger\" class=\"indirectLedger\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"wrap_result_group indirectLedger\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"float_r\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point\">공급가액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"indirect_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">세액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"indirect_vat\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">공급총액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"indirect_tot\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">수금액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"indirect_sukum\" readonly />\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"point ml10\">할인액</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"indirect_dc_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"wrap_foot\">\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\tCopyright ⓒ 2014 <span class=\"copy_fc\">HANA PHARM CO.</span>, LTD. All Right Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 엑셀 다운로드용 iframe -->\r\n");
      out.write("<iframe name=\"excelDownFrame\" frameBorder=\"0\" width=\"0\" height=\"0\" class=\"blind\"></iframe>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
