/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-04-28 07:04:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.business;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hanaph.saleon.member.vo.LoginUserVO;
import com.hanaph.saleon.common.utils.StringUtil;
import com.hanaph.saleon.common.utils.WebUtil;

public final class customerBalanceList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1430124365934L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/sessionCheck.jsp", Long.valueOf(1430193978042L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LoginUserVO loginUserVO = (LoginUserVO) session.getAttribute("onlineUser");	//세션생성 세션에서 emp_code를 가져온다.
	
	String userEmpCode  = "";		// 사원 코드
	String userEmpName  = "";		// 사원 이름
	String userEmpGb    = "";		// 사원 구분 
	String userDeptCode = "";		// 부서코드
	String userDeptName = "";		// 부서명
	String userGradeName = "";		// 사원 Grade Name
	String userDeptCd = "";			//hanahr 부서정보
	String userAssgnCd = "";			//직책 코드
	String userAssgnName = "";			//직책 코드명
	/*
	 * 로그인 정보가 있는경우
	 */
	if(loginUserVO != null){
		userEmpCode = StringUtil.nvl(loginUserVO.getEmp_code());    	// 사용자코드
		userEmpName = StringUtil.nvl(loginUserVO.getEmp_name());		// 사용자명
		userEmpGb = StringUtil.nvl(loginUserVO.getEmp_gb());			// 사용자 구분 코드
		userDeptCode = StringUtil.nvl(loginUserVO.getDept_code());  	// 부서 코드
		userDeptName = StringUtil.nvl(loginUserVO.getDept_name());		// 부서 명
		userGradeName = StringUtil.nvl(loginUserVO.getGrade_name());	// 사용자 부서명
		userDeptCd = StringUtil.nvl(loginUserVO.getDept_cd());  	    // 부서 코드
		userAssgnCd = StringUtil.nvl(loginUserVO.getAssgn_cd());  	    // 직책 코드
		userAssgnName = StringUtil.nvl(loginUserVO.getAssgn_name());  	// 직책 코드명
	}
	
	/* 현재 URI에 해당하는 프로그램 No(pgm_no) */
	String currPgmNoByUri = request.getAttribute("pgm_no") == null ? "" : (String) request.getAttribute("pgm_no");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	com.hanaph.saleon.common.utils.Environment env = new com.hanaph.saleon.common.utils.Environment();	//환경 변수
	
	String HTTPS_ONLINE_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_ONLINE_ROOT = env.getValue("https.root_dir.url");
	String ONLINE_WEB_ROOT = env.getValue("web_root_dir.url");		//URL 프로토콜, 도메인, 포트, 서브컨텍스트명, web디렉토리
	String ONLINE_ROOT = env.getValue("root_dir.url");				//URL 프로토콜, 도메인, 포트, 서브컨텍스트명
	String JDBC_URL = env.getValue("jdbc.url");
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar ONLINE_ROOT = \"");
      out.print(ONLINE_ROOT );
      out.write("\";\t\t/*환경변수*/\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/placeholders.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/easyui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/jquery-ui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui.theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/gw_sample.css\">");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/ui.jqgrid.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/grid.locale-kr.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar saleActionFlag = false;\t\t//기능(엑셀, 인쇄) 제어를 위한 전역변수\r\n");
      out.write("\tvar selectedCustomerId = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\t/* 화면의 Dom 객체가 모두 준비되었을 때 */\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 잔고/담보현황 jqGrid 생성 및 options 설정. */\r\n");
      out.write("\t\t$(\"#customer_detail\").jqGrid({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmtype:\"post\",\t\t// 요청방식\r\n");
      out.write("\t\t\tdatatype:\"json\",\t\t// 결과물 받을 데이터 타입\r\n");
      out.write("\t\t\tcolNames:[\"담보종류\",\"매출담보금액\",\"만기일\",\"어음번호\",\"발행처\",\"지급처\",\"발행일\",\"출고일\"],\t\t// 컬럼명\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"bill_gb\",\t\tindex:\"bill_gb\",\t\talign:\"center\",\twidth:100 },\t//담보종류\r\n");
      out.write("\t\t\t\t\t\t{name:\"sale_dambo_amt\",\tindex:\"sale_dambo_amt \",align:\"right\",\twidth:120 ,formatter:Commons.integerFmt},//매출담보금액\r\n");
      out.write("\t\t\t\t\t\t{name:\"end_ymd\",\t\tindex:\"end_ymd\", \t\talign:\"center\",\twidth:120},\t\t//만기일\r\n");
      out.write("\t\t\t\t\t\t{name:\"bill_no\",\t\tindex:\"bill_no\", \t\talign:\"center\",\twidth:150,},\t//어음번호\r\n");
      out.write("\t\t\t\t\t\t{name:\"balhang\",\t\tindex:\"balhang\", \t\talign:\"left\", \twidth:150, },\t//발행처\r\n");
      out.write("\t\t\t\t\t\t{name:\"jigeub\",\t\t\tindex:\"jigeub\", \t\talign:\"left\", \twidth:200, },\t//지급처\r\n");
      out.write("\t\t\t\t\t\t{name:\"start_ymd\",\t\tindex:\"start_ymd\", \t\talign:\"center\", width:120, },\t//발행일\r\n");
      out.write("\t\t\t\t\t\t{name:\"chulgo_ymd\",\t\tindex:\"chulgo_ymd\", \talign:\"center\",\twidth:120, },\t//출고일\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\theight:325,\t\t\t// 높이\r\n");
      out.write("\t\t\tpage: 1,\t\t\t// 기본 페이지 번호\r\n");
      out.write("\t\t\trowNum: 20,\t\t\t// row갯수\r\n");
      out.write("\t\t\trownumbers: true, \t// 행 번호\r\n");
      out.write("\t\t\trowList: [20,30,40],// 갯수 옵션\r\n");
      out.write("\t\t\tautowidth:true,\t\t// 자동 가로 사이즈\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tloadComplete: function(data){\t//조회 완료시 호출되는 function\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t*\t잔고/담보현황 조회 결과가 있을 경우 상단 정보 셋팅\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\tvar jasu_amt = 0;\r\n");
      out.write("\t\t\t\tvar cur_amt =0;\r\n");
      out.write("\t\t\t\tvar sum_cur_jasu = 0;\r\n");
      out.write("\t\t\t\tvar rate_dmbo = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.records > 0){\t\t//조회 결과가 있을 경우\r\n");
      out.write("\t\t\t\t\tjasu_amt = data.sumBalance.jasu_amt;\r\n");
      out.write("\t\t\t\t\tcur_amt = data.sumBalance.cur_amt;\r\n");
      out.write("\t\t\t\t\tsum_cur_jasu = jasu_amt + cur_amt;\t\t\r\n");
      out.write("\t\t\t\t\tsale_dambo_amt = data.sumBalance.sale_dambo_amt;\r\n");
      out.write("\t\t\t\t\trate_dmbo = Math.round( (sale_dambo_amt/sum_cur_jasu) * 100, 0 );\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#before_amt\").val(Commons.integerFmt(data.sumBalance.before_amt));\t//전월잔고\r\n");
      out.write("\t\t\t\t\t$(\"#jasu_amt\").val(Commons.integerFmt(jasu_amt));\t\t\t\t\t\t//미도래(자수)\r\n");
      out.write("\t\t\t\t\t$(\"#cur_amt\").val(Commons.integerFmt(cur_amt));\t\t\t\t\t\t\t//현잔고\r\n");
      out.write("\t\t\t\t\t$(\"#sum_cur_jasu\").val(Commons.integerFmt(sum_cur_jasu));\t\t\t\t//총여신\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#sale_amt\").val(Commons.integerFmt(data.sumBalance.sale_amt));\t\t//금월판매\r\n");
      out.write("\t\t\t\t\t$(\"#tasu_amt\").val(Commons.integerFmt(data.sumBalance.tasu_amt));\t\t//미도래(타수)\r\n");
      out.write("\t\t\t\t\t$(\"#sale_dambo_amt\").val(Commons.integerFmt(sale_dambo_amt));\t\t\t//담보확보액\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(rate_dmbo==Infinity || isNaN(rate_dmbo)){\r\n");
      out.write("\t\t\t\t\t\t$(\"#rate_dmbo_cur\").val(\"\");\t\t\t\t\t\t\t\t\t\t//담보확보율\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#rate_dmbo_cur\").val(rate_dmbo+\"%\");\t\t\t\t\t\t\t\t//담보확보율\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tsaleActionFlag = true;\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tsaleActionFlag = false;\r\n");
      out.write("\t\t\t\t\talert(\"해당 잔고/담보 자료가 없습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tpager: \"#customer_detail_pager\"\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 거래처 코드,거래처 명 grid 생성. */\r\n");
      out.write("\t\t$(\"#customer_grid_list\").jqGrid({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmtype:\"post\",\t\t// 요청방식\r\n");
      out.write("\t\t\tdatatype:\"json\",\t\t\t\t\t\t// 결과물 받을 데이터 타입\r\n");
      out.write("\t\t\tcolNames:[\"거래처코드\",\"거래처명\"],\t\t// 컬럼명\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_id\",\t\tindex:\"cust_id\",\t\talign:\"left\",\twidth:100, key:true},\t// 거래처코드\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_nm\",\t\tindex:\"cust_nm \",\t\talign:\"left\",\twidth:120}, \t\t\t//거래처명\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:436,\r\n");
      out.write("\t\t\trowNum: -1,\r\n");
      out.write("\t\t\tautowidth:true,\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tonSelectRow: function(id){\r\n");
      out.write("\t\t\t\tselectedCustomerId = id;\r\n");
      out.write("\t\t\t\tgetCustomerBalanceGridDetail(id);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tloadComplete: function(data){\t//조회 완료시 호출되는 function\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.records == 0){\t\t//조회 결과가 있을 경우\r\n");
      out.write("\t\t\t\t\talert(\"해당 거래처가 없습니다.\");\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tselectedCustomerId = data.rows[0].cust_id;\r\n");
      out.write("\t\t\t\t\t$(\"#customer_grid_list\").jqGrid('setSelection', selectedCustomerId);\r\n");
      out.write("\t\t\t\t\tgetCustomerBalanceGridDetail(selectedCustomerId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 조회 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#ct_retrieve_btn_type01\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgetCustomerBalanceGridList();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 인쇄 버튼 클릭\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t$(\"#p_print\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgridPrint();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 엑셀 버튼 클릭\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t$(\"#p_excel\").on(\"click\",function(){\r\n");
      out.write("\t\t\tCommons.extraAction(saleActionFlag, 'excel', '");
      out.print(ONLINE_ROOT);
      out.write("/business/customerBalanceDetailExcel.do?customerId='+selectedCustomerId, '');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 닫기 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_close\").on(\"click\",function(){\r\n");
      out.write("\t\t\tparent.Commons.closeTab('잔고|담보현황');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 거래구분 담보거래처 기본 셋팅 */\r\n");
      out.write("\t\t$(\":radio[name='gubun']:radio[value='0']\").attr('checked', true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 브라우저 창의 사이즈가 변경될 때 */\r\n");
      out.write("    $(window).resize(function(){\r\n");
      out.write("\t\t$(\"#customer_detail\").setGridWidth($('.box_type03 h372 mt15').width(), true);\t//grid 영역의 넓이가 동적으로 조절 \r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("    /* 윈도우의 모든 객체/파일이 로드 완료되었을 때 */\r\n");
      out.write("\t$(window).load(function(){\r\n");
      out.write("\t\t$(\"body\").on(\"keydown\", function(event){\r\n");
      out.write("\t\t\tif($(\"#ct_retrieve_btn_type01\").prop('disabled') == false){\r\n");
      out.write("\t\t\t\tif(event.keyCode==13 && event.target.name!=\"grid_count\"){\r\n");
      out.write("\t\t\t\t\tgetCustomerBalanceGridList();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * grid 조회\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction getCustomerBalanceGridList(){\r\n");
      out.write("\t\tvar customerId = $(\"#as_cust_id\").val();\r\n");
      out.write("\t\tvar gubun = $(\":radio[name='gubun']:checked\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(customerId == \"\"){\r\n");
      out.write("\t\t\t$(\"#as_cust_id_name\").val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#customer_grid_list\").jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/customerBalanceGridList.do?customerId=\"+customerId+\"&gubun=\"+gubun}).trigger(\"reloadGrid\", [{page:1}]);\t// 호출\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * grid 조회\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction getCustomerBalanceGridDetail(id){\r\n");
      out.write("\t\tvar customerId = id;\r\n");
      out.write("\t\t$(\"#customer_detail\").jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/customerBalanceGridDetail.do?customerId=\"+customerId}).trigger(\"reloadGrid\", [{page:1}]);\t// 호출\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 프린트를 하기위해 grid 재생성 \r\n");
      out.write("\t */\r\n");
      out.write("\tfunction gridPrint(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar customerId = selectedCustomerId;\r\n");
      out.write("\t\tvar grid = $(\"#customer_detail\");\r\n");
      out.write("\t\tvar page = $('.ui-pg-input').val();\r\n");
      out.write("\t\tvar rows=grid.getCol('bill_gb',true,'count');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#customerBalance').html('<table id=\\\"grid_list_clone\\\"></table>');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#grid_list_clone\").jqGrid({\r\n");
      out.write("\t\t\turl:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/customerBalanceGridDetail.do?customerId=\"+customerId,\r\n");
      out.write("\t\t\t// 요청방식\r\n");
      out.write("\t\t\tmtype:\"post\",\r\n");
      out.write("\t\t\t// 결과물 받을 데이터 타입\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\t// 컬럼명\r\n");
      out.write("\t\t\tcolNames:[\"담보종류\",\"매출담보금액\",\"만기일\",\"어음번호\",\"발행처\",\"지급처\",\"발행일\",\"출고일\"],\t\t// 컬럼명\r\n");
      out.write("\t\t\t// 컬럼 데이터(추가, 삭제, 수정이 가능하게 하려면 autoincrement컬럼을 제외한 모든 컬럼을 editable:true로 지정)\r\n");
      out.write("\t\t\t// edittyped은 text, password, ... input type명을 사용 \r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"bill_gb\",\t\tindex:\"bill_gb\",\t\talign:\"center\",\twidth:100 },//담보종류\r\n");
      out.write("\t\t\t\t\t\t{name:\"sale_dambo_amt\",\tindex:\"sale_dambo_amt \",align:\"right\",\twidth:120 ,formatter:Commons.integerFmt},//매출담보금액\r\n");
      out.write("\t\t\t\t\t\t{name:\"end_ymd\",\t\tindex:\"end_ymd\", \t\talign:\"center\",\twidth:120},\t\t//만기일\r\n");
      out.write("\t\t\t\t\t\t{name:\"bill_no\",\t\tindex:\"bill_no\", \t\talign:\"center\",\twidth:150,},\t//어음번호\r\n");
      out.write("\t\t\t\t\t\t{name:\"balhang\",\t\tindex:\"balhang\", \t\talign:\"left\", \twidth:150, },\t//발행처\r\n");
      out.write("\t\t\t\t\t\t{name:\"jigeub\",\t\t\tindex:\"jigeub\", \t\talign:\"left\", \twidth:200, },\t//지급처\r\n");
      out.write("\t\t\t\t\t\t{name:\"start_ymd\",\t\tindex:\"start_ymd\", \t\talign:\"center\", width:120, },\t//발행일\r\n");
      out.write("\t\t\t\t\t\t{name:\"chulgo_ymd\",\t\tindex:\"chulgo_ymd\", \talign:\"center\",\twidth:120, },\t//출고일\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t// 그리드(페이지)마다 보여줄 행의 수 -> 매개변수이름은 \"rows\"로 요청된다.\r\n");
      out.write("\t\t\tpage: page,\r\n");
      out.write("\t\t\trowNum: rows,\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tCommons.extraAction(saleActionFlag, 'print', '");
      out.print(ONLINE_ROOT);
      out.write("/common/commonPrint.do', 'customerBalance');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"frm\" id=\"frm\">\r\n");
      out.write("\t\t<!-- ##### content start ##### -->\r\n");
      out.write("\t\t<div class=\"wrap_search mbn\">\r\n");
      out.write("\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t<label>거래처</label>\r\n");
      out.write("\t\t\t\t<input name=\"as_cust_id\" id=\"as_cust_id\" class=\"w140\" type=\"text\" />\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn_search\" onclick=\"javascript:Commons.popupOpen('as_cust_id', '");
      out.print(ONLINE_ROOT);
      out.write("/business/common/customerList.do', '600', '655');\" ><span class=\"blind\">찾기</span></button>\r\n");
      out.write("\t\t\t\t<input name=\"as_cust_id_name\" id=\"as_cust_id_name\" type=\"text\" class=\"w140 ipt_disable\" />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"ml10\">거래구분</label>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gubun\" id=\"gubun\" value= \"0\" /><label for=\"cle1\">담보거래처</label>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gubun\" id=\"gubun\" value= \"1\" /><label for=\"cle2\">전체거래처</label>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"wrap_search_btn\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "ct_"));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"inner_cont sb_cont\">\t\t\r\n");
      out.write("\t\t\t<div class=\"wrap_btn_group mb10\">\r\n");
      out.write("\t\t\t\t<div class=\"btn_group ta_r\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "p_"));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<div class=\"wrap_customer01\">\r\n");
      out.write("\t\t\t\t<div class=\"wrap_search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_type01 float_l\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"customer_grid_list\"></table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"float_r\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search_type02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w46 ta_r\">전월잔고</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"before_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">미도래(자수)</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"jasu_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">현잔고</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"cur_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">총여신</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"sum_cur_jasu\" readonly><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w46 ta_r\">금월판매</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"sale_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">미도래(타수)</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"tasu_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">담보확보액</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"sale_dambo_amt\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"w70 ta_r\">담보확보율</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"w140 ta_right ipt_disable\" id=\"rate_dmbo_cur\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box_type03 h372 mt15\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"customer_detail\"></table>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"customer_detail_pager\"></div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ##### content end ##### -->\r\n");
      out.write("\t</form>\t\r\n");
      out.write("\t<div id=\"customerBalance\" style=\"display:none;\"><table id=\"grid_list_clone\"></table></div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"wrap_foot\">\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\tCopyright ⓒ 2014 <span class=\"copy_fc\">HANA PHARM CO.</span>, LTD. All Right Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 엑셀 다운로드용 iframe -->\r\n");
      out.write("<iframe name=\"excelDownFrame\" frameBorder=\"0\" width=\"0\" height=\"0\" class=\"blind\"></iframe>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
