/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-04-28 04:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.business;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hanaph.saleon.member.vo.LoginUserVO;
import com.hanaph.saleon.common.utils.StringUtil;
import com.hanaph.saleon.common.utils.WebUtil;
import com.hanaph.saleon.business.vo.BusinessVO;

public final class orderApprovalSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1430124365934L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1421734197738L));
    _jspx_dependants.put("/common/sessionCheck.jsp", Long.valueOf(1430193978042L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LoginUserVO loginUserVO = (LoginUserVO) session.getAttribute("onlineUser");	//세션생성 세션에서 emp_code를 가져온다.
	
	String userEmpCode  = "";		// 사원 코드
	String userEmpName  = "";		// 사원 이름
	String userEmpGb    = "";		// 사원 구분 
	String userDeptCode = "";		// 부서코드
	String userDeptName = "";		// 부서명
	String userGradeName = "";		// 사원 Grade Name
	String userDeptCd = "";			//hanahr 부서정보
	String userAssgnCd = "";			//직책 코드
	String userAssgnName = "";			//직책 코드명
	/*
	 * 로그인 정보가 있는경우
	 */
	if(loginUserVO != null){
		userEmpCode = StringUtil.nvl(loginUserVO.getEmp_code());    	// 사용자코드
		userEmpName = StringUtil.nvl(loginUserVO.getEmp_name());		// 사용자명
		userEmpGb = StringUtil.nvl(loginUserVO.getEmp_gb());			// 사용자 구분 코드
		userDeptCode = StringUtil.nvl(loginUserVO.getDept_code());  	// 부서 코드
		userDeptName = StringUtil.nvl(loginUserVO.getDept_name());		// 부서 명
		userGradeName = StringUtil.nvl(loginUserVO.getGrade_name());	// 사용자 부서명
		userDeptCd = StringUtil.nvl(loginUserVO.getDept_cd());  	    // 부서 코드
		userAssgnCd = StringUtil.nvl(loginUserVO.getAssgn_cd());  	    // 직책 코드
		userAssgnName = StringUtil.nvl(loginUserVO.getAssgn_name());  	// 직책 코드명
	}
	
	/* 현재 URI에 해당하는 프로그램 No(pgm_no) */
	String currPgmNoByUri = request.getAttribute("pgm_no") == null ? "" : (String) request.getAttribute("pgm_no");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	com.hanaph.saleon.common.utils.Environment env = new com.hanaph.saleon.common.utils.Environment();	//환경 변수
	
	String HTTPS_ONLINE_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_ONLINE_ROOT = env.getValue("https.root_dir.url");
	String ONLINE_WEB_ROOT = env.getValue("web_root_dir.url");		//URL 프로토콜, 도메인, 포트, 서브컨텍스트명, web디렉토리
	String ONLINE_ROOT = env.getValue("root_dir.url");				//URL 프로토콜, 도메인, 포트, 서브컨텍스트명
	String JDBC_URL = env.getValue("jdbc.url");
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	/* 사용자 정보 셋팅(부서코드, pda 권한) */
	BusinessVO commonEmpInfo = new BusinessVO();
	commonEmpInfo = (BusinessVO)request.getAttribute("commonEmpInfo");
	
	boolean isNull = true; // null flag
	String dept_cd = ""; // 부서코드
	String pda_auth = ""; // pda 권한
	
	if(null != commonEmpInfo) { // null이 아닐 경우
		dept_cd = commonEmpInfo.getDept_cd();
		pda_auth = commonEmpInfo.getPda_auth();
		isNull = false;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar ONLINE_ROOT = \"");
      out.print(ONLINE_ROOT );
      out.write("\";\t\t/*환경변수*/\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/placeholders.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/easyui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/jquery-ui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui.theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/gw_sample.css\">");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/css/ui.jqgrid.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/grid.locale-kr.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/formCheck.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ONLINE_WEB_ROOT);
      out.write("/js/business.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar searchActionFlag = false; // 판매현황 부가기능(인쇄, 엑셀다운로드) 사용 가능 여부 flag\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 사원 정보 존재 여부 */\r\n");
      out.write("\t\tif (");
      out.print(isNull);
      out.write(") {\r\n");
      out.write("\t\t\talert(\"사원정보 자료가 없습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* jqGrid의 jsonReader 옵션 전역 설정. row 반복 형태의 json 처리.  */\r\n");
      out.write("\t    jsonReader : {\r\n");
      out.write("            repeatitems: false;\r\n");
      out.write("    \t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t/* 상세 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_detail\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"제품코드\",\"제품명\", \"규격\", \"요청수량\", \"승인수량\", \"단가\", \"공급가액\", \"세액\", \"공급총액\", \"사전 %\", \"할인단가\", \"할인액\", \"색상\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"item_id\",\tindex:\"item_id\",\talign:\"center\", width:50},\r\n");
      out.write("\t\t\t\t\t\t{name:\"item_nm\",\tindex:\"item_nm\", \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"standard\",\tindex:\"standard\",\talign:\"left\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"req_qty\",\tindex:\"req_qty\",\talign:\"right\", width:50},\r\n");
      out.write("\t\t\t\t\t\t{name:\"qty\",\t\tindex:\"qty\",\t\talign:\"right\", width:50},\r\n");
      out.write("\t\t\t\t\t\t{name:\"danga\",\t\tindex:\"danga\", \t\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"amt\",\t\tindex:\"amt\", \t\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"vat\",\t\tindex:\"vat\", \t\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"tot_amt\",\tindex:\"tot_amt\",\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rate\",\t\tindex:\"rate\", \t\talign:\"right\", width:50},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dc_danga\",\tindex:\"dc_danga\",\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"dc_amt\",\t\tindex:\"dc_amt\",\t\talign:\"right\", width:100, formatter:amountFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"color\",\t\tindex:\"color\",\t\thidden:true}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* row 추가될때마다 실행 */\r\n");
      out.write("\t\t\tafterInsertRow:function(rowid, rowdata , rowelem){\r\n");
      out.write("\t\t\t\tif (rowdata.color == \"R\") {\r\n");
      out.write("\t\t\t\t\t$(\"#grid_list_detail tr[id=\" + rowid + \"]\").css('color', 'red');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tvar amt = data.totalCountInfo.total_amt;\r\n");
      out.write("\t\t\t\t\tvar vat = data.totalCountInfo.total_vat;\r\n");
      out.write("\t\t\t\t\tvar tot_amt = data.totalCountInfo.total_tot_amt;\r\n");
      out.write("\t\t\t\t\tvar dc_amt = data.totalCountInfo.total_dc_amt;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#amt\").val(Commons.addComma(amt)); // 공급가액\r\n");
      out.write("\t\t\t\t\t$(\"#vat\").val(Commons.addComma(vat)); // 세액\r\n");
      out.write("\t\t\t\t\t$(\"#tot_amt\").val(Commons.addComma(tot_amt)); // 공급총액\r\n");
      out.write("\t\t\t\t\t$(\"#dc_amt\").val(Commons.addComma(dc_amt)); // 할인액\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsearchActionFlag = true; // 인쇄, 엑셀 사용 가능하도록\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\tsearchActionFlag = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_detail\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t/* 승인조회 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_approval\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"주문승인일\",\"승인일시\",\"거래처\",\"거래처명\",\"판매처\",\"판매처명\",\"승인번호\",\"승인구분\",\"승인사번\",\"승인사원명\",\"주문요청일\",\"접수번호\",\"주문종류\",\"요청사항\",\"승인/반려사유\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"app_ymd\",\t\tindex:\"app_ymd\", \t\talign:\"center\", width:80},\r\n");
      out.write("\t\t\t\t\t\t{name:\"app_time\",\t\tindex:\"app_time\", \t\talign:\"center\"},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_id\",\t\tindex:\"cust_id\", \t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_nm\",\t\tindex:\"cust_nm\", \t\talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_id\",\t\tindex:\"rcust_id\", \t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_nm\",\t\tindex:\"rcust_nm\", \t\talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"app_no\",\t\t\tindex:\"app_no\", \t\talign:\"center\", width:110, formatter:Commons.gumaeNo},\r\n");
      out.write("\t\t\t\t\t\t{name:\"status\",\t\t\tindex:\"status\", \t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"asawon_id\",\t\tindex:\"asawon_id\", \t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"asawon_nm\",\t\tindex:\"asawon_nm\", \t\talign:\"left\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"ymd\",\t\t\tindex:\"ymd\", \t\t\talign:\"center\", width:80},\r\n");
      out.write("\t\t\t\t\t\t{name:\"gumae_no\",\t\tindex:\"gumae_no\", \t\talign:\"center\", width:110, formatter:Commons.gumaeNo},\r\n");
      out.write("\t\t\t\t\t\t{name:\"gumae_gb\",\t\tindex:\"gumae_gb\",\t \talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"bigo\",\t\t\tindex:\"bigo\",\t\t\talign:\"left\", width:200},\r\n");
      out.write("\t\t\t\t\t\t{name:\"return_desc\",\tindex:\"return_desc\",\talign:\"left\", width:200}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_approval\").setSelection(1, true); // 첫번째 row 선택\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#grid_list_detail\").jqGrid(\"clearGridData\"); // 상세 영역 초기화\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* row 선택 시 */\r\n");
      out.write("\t\t\tonSelectRow: function(){\r\n");
      out.write("\t\t\t\tvar id = $(\"#grid_list_approval\").jqGrid('getGridParam','selrow'); // 현재 선택한 row의 id\r\n");
      out.write("\t\t\t\tvar ret = $(\"#grid_list_approval\").jqGrid('getRowData',id); // 현재 row의 정보\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgetOrderApprovalDetailGridList(ret.ymd, ret.gumae_no); // 상세 내역 목록 조회\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_approval\"\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 주문조회 목록 grid */\r\n");
      out.write("\t\t$(\"#grid_list_order\").jqGrid({\r\n");
      out.write("\t\t\tmtype:\"get\",\r\n");
      out.write("\t\t\tdatatype:\"json\",\r\n");
      out.write("\t\t\tcolNames:[\"주문요청일\",\"거래처\",\"거래처명\",\"판매처\",\"판매처명\",\"주문시간\",\"접수번호\",\"위반주문\",\"팀장승인\",\"주문상태\",\"주문종류\",\"비고\"],\r\n");
      out.write("\t\t\tcolModel:[\r\n");
      out.write("\t\t\t\t\t\t{name:\"ymd\",\t\t\t\t\tindex:\"ymd\", \t\t\t\t\talign:\"center\", width:80},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_id\",\t\t\t\tindex:\"cust_id\", \t\t\t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"cust_nm\",\t\t\t\tindex:\"cust_nm\", \t\t\t\talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_id\",\t\t\t\tindex:\"rcust_id\",\t\t\t \talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"rcust_nm\",\t\t\t\tindex:\"rcust_nm\",\t\t\t \talign:\"left\", width:150},\r\n");
      out.write("\t\t\t\t\t\t{name:\"req_time\",\t\t\t\tindex:\"req_time\",\t\t\t \talign:\"center\", width:90},\r\n");
      out.write("\t\t\t\t\t\t{name:\"gumae_no\",\t\t\t\tindex:\"gumae_no\",\t\t\t \talign:\"center\", width:110, formatter:Commons.gumaeNo},\r\n");
      out.write("\t\t\t\t\t\t{name:\"wiban_order_req_yn\",\t\tindex:\"wiban_order_req_yn\",\t\talign:\"center\", width:60, formatter:wibanFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"wiban_order_conf_yn\",\tindex:\"wiban_order_conf_yn\", \talign:\"center\", width:60, formatter:confirmFormatter},\r\n");
      out.write("\t\t\t\t\t\t{name:\"status\",\t\t\t\t\tindex:\"status\",\t\t\t\t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"gumae_gb\",\t\t\t\tindex:\"gumae_gb\",\t\t\t\talign:\"center\", width:60},\r\n");
      out.write("\t\t\t\t\t\t{name:\"return_desc\",\t\t\tindex:\"return_desc\",\t\t\talign:\"left\", width:200}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\theight:231,\r\n");
      out.write("\t\t\trownumWidth : 30,\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\trowNum: 20,\r\n");
      out.write("\t\t\trownumbers: true, \r\n");
      out.write("\t\t\trowList: [20,30,40],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 조회 완료 시 호출 */\r\n");
      out.write("\t\t\tloadComplete: function(data){\r\n");
      out.write("\t\t\t\tif (data.records > 0) {\r\n");
      out.write("\t\t\t\t\tif(data.page == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#grid_list_order\").setSelection(1, true); // 첫번째 row 선택\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#grid_list_detail\").jqGrid(\"clearGridData\"); // 상세 영역 초기화\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* row 선택 시 */\r\n");
      out.write("\t\t\tonSelectRow: function(){\r\n");
      out.write("\t\t\t\tvar id = $(\"#grid_list_order\").jqGrid('getGridParam','selrow'); // 현재 선택한 row의 id\r\n");
      out.write("\t\t\t\tvar ret = $(\"#grid_list_order\").jqGrid('getRowData',id); // 현재 row의 정보\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgetOrderApprovalDetailGridList(ret.ymd, ret.gumae_no); // 상세 내역 목록 조회\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpager: \"#grid_Pager_order\"\r\n");
      out.write("   \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 조회 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#ct_retrieve_btn_type02\").on(\"click\",function(){\r\n");
      out.write("\t\t\tgetOrderApprovalSearchGridList();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 인쇄 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_print\").on(\"click\",function(){\r\n");
      out.write("\t\t\tvar selectType = $(\"#selectType option:selected\").val();\r\n");
      out.write("\t\t\tCommons.extraAction(searchActionFlag, 'print', '");
      out.print(ONLINE_ROOT);
      out.write("/common/commonPrint.do', selectType);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 엑셀 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_excel\").on(\"click\",function(){\r\n");
      out.write("\t\t\tCommons.extraAction(searchActionFlag, 'excel', '");
      out.print(ONLINE_ROOT);
      out.write("/business/orderApprovalSearchGridListExcelDown.do', '');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 닫기 버튼 클릭 */\r\n");
      out.write("\t\t$(\"#p_close\").on(\"click\",function(){\r\n");
      out.write("\t\t\tparent.Commons.closeTab('주문/승인 조회');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 조회일자 셋팅(이번 달 1일 ~ 오늘) */\r\n");
      out.write("\t\tCommons.setDate(\"adt_fr_date\", \"adt_to_date\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* grid 영역 넓이 셋팅 */\r\n");
      out.write("\t\tvar width = $(\"#order\").width();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#grid_list_order\").setGridWidth(width , false);\r\n");
      out.write("\t\t$(\"#grid_list_approval\").setGridWidth(width , false);\r\n");
      out.write("\t\t$(\"#grid_list_detail\").setGridWidth(width , false);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 엔터키 눌렸을 경우 조회되도록. */\r\n");
      out.write("\t\t$(\"body\").on(\"keydown\", function(event){\r\n");
      out.write("\t\t\tif($(\"#ct_retrieve_btn_type02\").prop('disabled') == false){\r\n");
      out.write("\t\t\t\tif(event.keyCode==13 && event.target.name!=\"grid_count\"){\r\n");
      out.write("\t\t\t\t\tgetOrderApprovalSearchGridList();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 브라우저 창의 사이즈가 변경될 때 */\r\n");
      out.write("\t$(window).resize(function(){\r\n");
      out.write("\t\tvar width = $(\"#order\").width();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#grid_list_order\").setGridWidth(width , false);\r\n");
      out.write("\t\t$(\"#grid_list_approval\").setGridWidth(width , false);\r\n");
      out.write("\t\t$(\"#grid_list_detail\").setGridWidth(width , false);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 주문/승인 목록조회 */\r\n");
      out.write("\tfunction getOrderApprovalSearchGridList(){\r\n");
      out.write("\t\tvar selectType = $(\"#selectType option:selected\").val();\r\n");
      out.write("\t\tvar adt_fr_date = $(\"#adt_fr_date\").val();\r\n");
      out.write("\t\tvar adt_to_date = $(\"#adt_to_date\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 유효성 체크 */\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(adt_fr_date)) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#ad_fr_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!formCheck.isDateFormat(adt_to_date)) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#ad_to_date\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (formCheck.dateChk(adt_fr_date, adt_to_date) < 0) {\r\n");
      out.write("\t\t\talert(\"조회 기간을 확인하세요!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 파라미터 셋팅 */\r\n");
      out.write("\t\tvar paramStr = $(\"#frm\").serialize();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 호출 */\r\n");
      out.write("\t\t$(\"#grid_list_\" + selectType).jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/orderApprovalSearchGridList.do?\" + paramStr}).trigger(\"reloadGrid\", [{page:1}]);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 주문/승인 상세 목록 조회 */\r\n");
      out.write("\tfunction getOrderApprovalDetailGridList(ymd, gumae_no){\r\n");
      out.write("\t\t/* 파라미터 셋팅 */\r\n");
      out.write("\t\tvar params = {\r\n");
      out.write("\t\t\tymd : ymd,\r\n");
      out.write("\t\t\tgumae_no : gumae_no,\r\n");
      out.write("\t\t\tselectType : $(\"#selectType option:selected\").val()\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar paramStr = $.param(params);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 호출 */\r\n");
      out.write("\t\t$(\"#grid_list_detail\").jqGrid('setGridParam',{url:\"");
      out.print(ONLINE_ROOT);
      out.write("/business/orderApprovalDetailGridList.do?\" + paramStr}).trigger(\"reloadGrid\", [{page:1}]);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 금액 커스텀 포맷 */\r\n");
      out.write("\tfunction amountFormatter(cellvalue){\r\n");
      out.write("\t\tvar returnValue = \"\";\r\n");
      out.write("\t\tif (\"0\" != cellvalue && \"\" != cellvalue) {\r\n");
      out.write("\t\t\treturnValue = Math.round(cellvalue);\r\n");
      out.write("\t\t\treturnValue = Commons.addComma(returnValue);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn returnValue.toString();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 위반주문 커스텀 포맷 */\r\n");
      out.write("\tfunction wibanFormatter(cellvalue){\r\n");
      out.write("\t\tvar returnValue = \"\";\r\n");
      out.write("\t\tif (\"N\" == cellvalue) {\r\n");
      out.write("\t\t\treturnValue = \"정상\";\r\n");
      out.write("\t\t} else if (\"Y\" == cellvalue) {\r\n");
      out.write("\t\t\treturnValue = \"위반\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn returnValue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 팀장승인 커스텀 포맷 */\r\n");
      out.write("\tfunction confirmFormatter(cellvalue){\r\n");
      out.write("\t\tvar returnValue = \"\";\r\n");
      out.write("\t\tif (\"0\" == cellvalue) {\r\n");
      out.write("\t\t\treturnValue = \"대기\";\r\n");
      out.write("\t\t} else if (\"1\" == cellvalue) {\r\n");
      out.write("\t\t\treturnValue = \"승인\";\r\n");
      out.write("\t\t} else if (\"2\" == cellvalue) {\r\n");
      out.write("\t\t\treturnValue = \"반려\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn returnValue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 조회유형에 따른 grid 영역 교체 */\r\n");
      out.write("\tfunction changeType(value) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (\"order\" == value) { // 주문 조회\r\n");
      out.write("\t\t\t$(\".type_order\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".type_approval\").css(\"display\", \"none\");\r\n");
      out.write("\t\t} else if (\"approval\" == value) { // 승인 조회\r\n");
      out.write("\t\t\t$(\".type_approval\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".type_order\").css(\"display\", \"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".gridArea\").hide();\r\n");
      out.write("\t\t$(\"#\" + value).show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#grid_list_detail\").jqGrid(\"clearGridData\"); // 상세영역 초기화\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 담보약속 팝업 */\r\n");
      out.write("\tfunction openPromisePopup(){\r\n");
      out.write("\t\tif (!searchActionFlag) { // 조회 결과가 없을 경우\r\n");
      out.write("\t\t\talert(\"조회 결과가 없습니다.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar selectType = $(\"#selectType option:selected\").val();\r\n");
      out.write("\t\tvar id = $(\"#grid_list_\" + selectType).jqGrid('getGridParam','selrow');\r\n");
      out.write("\t\tvar ret = $(\"#grid_list_\" + selectType).jqGrid('getRowData',id);\r\n");
      out.write("\t\tvar cust_id = ret.cust_id;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (\"\" == cust_id) {\r\n");
      out.write("\t\t\talert(\"주문내역을 선택해주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tCommons.popupOpen('promise', '");
      out.print(ONLINE_ROOT);
      out.write("/business/common/promiseList.do', '600', '655');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap_search\">\r\n");
      out.write("\t\t<form name=\"frm\" id=\"frm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_dept_cd\" id=\"as_dept_cd\" value=\"");
      out.print(dept_cd );
      out.write("\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"as_pda_auth\" id=\"as_pda_auth\" value=\"");
      out.print(pda_auth );
      out.write("\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<div class=\"float_l\">\r\n");
      out.write("\t\t\t\t<label class=\"w70 type_order\" style=\"display:inline-block;\">주문일</label>\r\n");
      out.write("\t\t\t\t<label class=\"w70 type_approval\" style=\"display:none;\">승인일</label>\r\n");
      out.write("\t\t\t\t<p class=\"wrap_date\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" maxlength=\"10\" id=\"adt_fr_date\" name=\"adt_fr_date\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">달력보기</span></button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t~\r\n");
      out.write("\t\t\t\t<p class=\"wrap_date\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" maxlength=\"10\" id=\"adt_to_date\" name=\"adt_to_date\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_date\"><span class=\"blind\">달력보기</span></button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"ml10\">조회구분</label>\r\n");
      out.write("\t\t\t\t<select id=\"selectType\" class=\"w100\" name=\"selectType\" onchange=\"javascript:changeType(this.value);\">\r\n");
      out.write("\t\t\t\t\t<option value=\"order\">주문조회</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"approval\">승인조회</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"type_order\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">주문상태</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"as_receipt_gb\" class=\"w100\" name=\"as_receipt_gb\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">접수</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">승인</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">반려</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"type_approval\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">승인구분</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"as_receipt_gb2\" class=\"w100\" name=\"as_receipt_gb2\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">승인</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">반려</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"ml10\">여신규정</label>\r\n");
      out.write("\t\t\t\t<select id=\"as_limit_yn\" class=\"w100\" name=\"as_limit_yn\">\r\n");
      out.write("\t\t\t\t\t<option value=\"A\">전체</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"N\">이내</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Y\">초과</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"E\">예외</option>\r\n");
      out.write("\t\t\t\t</select><br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"w70\">주문구분</label>\r\n");
      out.write("\t\t\t\t<select id=\"as_slip_gb\" class=\"w100\" name=\"as_slip_gb\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">온라인 주문</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">PDA 주문</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label class=\"ml10\">거래처</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" maxlength=\"10\" class=\"w140\" id=\"as_cust_id\" name=\"as_cust_id\" onblur=\"javascript:Business.getCustomerName(this.id);\"/>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn_search\" onclick=\"javascript:Commons.popupOpen('as_cust_id', '");
      out.print(ONLINE_ROOT);
      out.write("/business/common/customerList.do', '600', '655');\" ><span class=\"blind\">찾기</span></button>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"w200 ipt_disable\" id=\"as_cust_id_name\" name=\"as_cust_id_name\" readonly />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"type_order\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">주문위반</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"as_wiban_order_req_yn\" class=\"w100\" name=\"as_wiban_order_req_yn\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"%\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"N\">정상</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Y\">위반</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"type_order\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">팀장반려</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"as_wiban_order_conf_yn\" class=\"w100\" name=\"as_wiban_order_conf_yn\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"%\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">대기</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">승인</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">반려</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"type_approval\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<label class=\"ml10\">담보약속</label>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn_search\" onclick=\"javascript:openPromisePopup();\" ><span class=\"blind\">찾기</span></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"wrap_search_btn\">\r\n");
      out.write("\t\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "ct_"));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrap_btn_group\">\r\n");
      out.write("\t\t<div class=\"btn_group ta_r\">\r\n");
      out.write("\t\t\t");
      out.print(WebUtil.createButtonArea(currPgmNoByUri, "p_"));
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"inner_cont2\">\r\n");
      out.write("\t\t<div class=\"wrap_result_group\">\r\n");
      out.write("\t\t\t<!-- 주문 조회 -->\r\n");
      out.write("\t\t\t<div id=\"order\" class=\"gridArea\" style=\"margin-bottom:15px; display:block;\">\r\n");
      out.write("\t\t\t\t<table id=\"grid_list_order\"></table>\r\n");
      out.write("\t\t\t\t<div id=\"grid_Pager_order\" class=\"order\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 승인 조회 -->\r\n");
      out.write("\t\t\t<div id=\"approval\" class=\"gridArea\" style=\"margin-bottom:15px; display:none;\">\r\n");
      out.write("\t\t\t\t<table id=\"grid_list_approval\"></table>\r\n");
      out.write("\t\t\t\t<div id=\"grid_Pager_approval\" class=\"approval\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 상세 -->\r\n");
      out.write("\t\t\t<table id=\"grid_list_detail\"></table>\r\n");
      out.write("\t\t\t<div id=\"grid_Pager_detail\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"wrap_result_group\">\r\n");
      out.write("\t\t\t\t<div class=\"result_group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"float_r\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"point\">공급가액</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t<label class=\"point ml10\">세액</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"vat\" readonly />\r\n");
      out.write("\t\t\t\t\t\t<label class=\"point ml10\">공급총액</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"tot_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t\t<label class=\"point ml10\">할인액</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"w100 ta_right ipt_disable\" id=\"dc_amt\" readonly />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"wrap_foot\">\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\tCopyright ⓒ 2014 <span class=\"copy_fc\">HANA PHARM CO.</span>, LTD. All Right Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 엑셀 다운로드용 iframe -->\r\n");
      out.write("<iframe name=\"excelDownFrame\" frameBorder=\"0\" width=\"0\" height=\"0\" class=\"blind\"></iframe>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
