/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-11-09 04:09:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.pe.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hanaph.gw.co.common.utils.StringUtil;
import com.hanaph.gw.co.personnel.vo.DepartmentVO;
import com.hanaph.gw.pe.member.vo.MemberVO;
import javax.servlet.http.HttpSession;

public final class memberSelectPopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1424677116691L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1429838623000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
com.hanaph.gw.co.common.utils.Environment env = new com.hanaph.gw.co.common.utils.Environment();
	
	String HTTPS_GROUP_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_GROUP_ROOT = env.getValue("https.root_dir.url");
	String GROUP_WEB_ROOT = env.getValue("web_root_dir.url");
	String GROUP_ROOT = env.getValue("root_dir.url");
	String JDBC_URL = env.getValue("jdbc.url");
	
	
      out.write('\r');
      out.write('\n');

	List<DepartmentVO> departmentList = (List<DepartmentVO>)request.getAttribute("departmentList");
	String type = StringUtil.nvl((String)request.getAttribute("type"));
	String seq = StringUtil.nvl((String)request.getAttribute("seq"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>하나제약 그룹웨어</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/dtree.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui-1.10.4.custom.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery.bpopup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/dtree.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/formCheck.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 부모창에 값 전달\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction goMemberTarget(){\r\n");
      out.write("\t\tparent.addMemberRow(memberTargetList.document.getElementsByName(\"emp_no\"));\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap_authority_staff\">\r\n");
      out.write("\t<div class=\"authority_staff\">\r\n");
      out.write("\t\t<h3>임직원선택</h3>\r\n");
      out.write("\t\t<form name=\"frm\" id=\"frm\" method=\"post\" action=\"");
      out.print(GROUP_ROOT );
      out.write("/pe/member/memberSelectMemberIframe.do\">\r\n");
      out.write("\t\t\t<input type =\"hidden\" id=\"dept_cd\" name=\"dept_cd\">\r\n");
      out.write("\t\t\t<input type =\"hidden\" id=\"up_dept_gbn\" name=\"up_dept_gbn\">\r\n");
      out.write("\t\t\t<input type =\"hidden\" id=\"type\" name=\"type\" value=\"");
      out.print(type);
      out.write("\">\r\n");
      out.write("\t\t\t<input type =\"hidden\" id=\"seq\" name=\"seq\" value=\"");
      out.print(seq);
      out.write("\">\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"wrap_tree pst_rel\">\r\n");
      out.write("\t\t\t<div class=\"wrap_tree_btn pst_abs\" style=\"width:92px; margin:10px auto\">\r\n");
      out.write("\t\t\t\t<button class=\"type_01\" onclick=\"javascript: d.openAll();\">펼치기</button>\r\n");
      out.write("\t\t\t\t<button class=\"type_01\" onclick=\"javascript: d.closeAll();\">접기</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mt10\" style=\"margin-top:40px;\"></div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\td = new dTree('d');\r\n");
      out.write("\t\t\t\t");

				if(departmentList.size()!=0){
					for(int i=0; departmentList.size()>i;i++){
						DepartmentVO departmentVO = new DepartmentVO();
						departmentVO = departmentList.get(i);
						if(departmentVO.getUp_dept_cd().equals("9999")){
							departmentVO.setUp_dept_cd("-1");
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\td.add(\"");
      out.print(StringUtil.nvl(departmentVO.getDept_cd()));
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(StringUtil.nvl(departmentVO.getUp_dept_cd()) );
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(StringUtil.nvl(departmentVO.getDept_ko_nm()) );
      out.write("\",\"javascript:goLocation('");
      out.print(StringUtil.nvl(departmentVO.getDept_cd()));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(StringUtil.nvl(departmentVO.getUp_dept_gbn()));
      out.write("');\",\"");
      out.print(StringUtil.nvl(departmentVO.getDept_ko_nm()) );
      out.write("\");\r\n");
      out.write("\t\t\t\t");

					}
				}
				
      out.write("\r\n");
      out.write("\t\t\t\tdocument.write(d);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tfunction goLocation( dept_cd, up_dept_gbn){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"frm\").target= \"memberList\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"dept_cd\").value = dept_cd;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"up_dept_gbn\").value = up_dept_gbn;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"frm\").submit();\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"wrap_group\">\r\n");
      out.write("\t\t\t<iframe name=\"memberList\" src=\"");
      out.print(GROUP_ROOT );
      out.write("/pe/member/memberSelectMemberIframe.do?seq=");
      out.print(seq );
      out.write("&type=");
      out.print(type );
      out.write("\" width=\"303px;\" height=\"260px\" frameBorder=\"0\" border=\"0\"></iframe>\r\n");
      out.write("\t\t\t<iframe name=\"memberTargetList\" src=\"");
      out.print(GROUP_ROOT );
      out.write("/pe/member/memberSelectMemberTargetIframe.do?seq=");
      out.print(seq );
      out.write("&type=");
      out.print(type );
      out.write("\" width=\"303px;\" height=\"345px\" frameBorder=\"0\" border=\"0\"></iframe>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<button class=\"close\" onclick=\"window.parent.layerClose();\"><span class=\"blind\">닫기</span></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
