DROP VIEW USRBM.VIEW_SALES_BRNC;

/* Formatted on 2017-03-18 오전 10:55:56 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VIEW_SALES_BRNC
(
   RACEYY,
   RACETIMES,
   RACEDAYS,
   RACEDATE,
   RJANGCD,
   RACENO,
   TRACKCD,
   BRANCHCD,
   BRANCHNM,
   TOT_SALES
)
AS
     SELECT D.STND_YEAR AS RACEYY,
            D.TMS RACETIMES,
            D.DAY_ORD RACEDAYS,
            I.RACE_DAY RACEDATE,
            DECODE (D.MEET_CD, '003', '004', D.MEET_CD) RJANGCD,
            D.RACE_NO RACENO,
            '0' || DECODE (D.SELL_CD, '03', '04', D.SELL_CD) TRACKCD,
            D.COMM_NO BRANCHCD,
            C.CD_NM AS BRANCHNM,
            SUM (D.DIV_TOTAL) AS TOT_SALES
       FROM TBES_SDL_DT D, VW_SDL_INFO I, TBRK_SPEC_CD C
      WHERE     SELL_CD IN ('01', '03')
            AND D.MEET_CD = I.MEET_CD
            AND D.STND_YEAR = I.STND_YEAR
            AND D.TMS = I.TMS
            AND D.DAY_ORD = I.DAY_ORD
            AND D.COMM_NO = C.CD(+)
            AND C.GRP_CD = '060'
   GROUP BY DECODE (D.MEET_CD, '003', '004', D.MEET_CD),
            D.STND_YEAR,
            D.TMS,
            D.DAY_ORD,
            D.RACE_NO,
            '0' || DECODE (D.SELL_CD, '03', '04', D.SELL_CD),
            D.COMM_NO,
            C.CD_NM,
            I.RACE_DAY;
COMMENT ON TABLE USRBM.VIEW_SALES_BRNC IS '광명 지점별 매출액';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RACEYY IS '경주년도';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RACETIMES IS '회차';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RACEDAYS IS '일차';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RACEDATE IS '경주일';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RJANGCD IS '시행처(광명:001,미사리:003)';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.RACENO IS '경주';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.TRACKCD IS '판매처(광명:001,미사리:003)';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.BRANCHCD IS '지점코드';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.BRANCHNM IS '지점명';

COMMENT ON COLUMN USRBM.VIEW_SALES_BRNC.TOT_SALES IS '매출액';


GRANT SELECT ON USRBM.VIEW_SALES_BRNC TO BCRC;

GRANT SELECT ON USRBM.VIEW_SALES_BRNC TO CCRC;
