DROP VIEW USRBM.VIEW_SALES_BCRC_BOAT;

/* Formatted on 2017-03-18 오전 10:55:41 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VIEW_SALES_BCRC_BOAT
(
   RACEDATE,
   RACEYY,
   RACETIMES,
   RACEDAYS,
   CYCLECD,
   RACENO,
   OUTSITE,
   WIN,
   PLACE,
   EXACTA,
   QUINELLA,
   TRIELLA,
   REFUND,
   DIV_TOTAL
)
AS
   SELECT "RACEDATE",
          "RACEYY",
          "RACETIMES",
          "RACEDAYS",
          "CYCLECD",
          "RACENO",
          "OUTSITE",
          "WIN",
          "PLACE",
          "EXACTA",
          "QUINELLA",
          "TRIELLA",
          "REFUND",
          "WIN" + "PLACE" + "EXACTA" + "QUINELLA" + "TRIELLA" + "REFUND"
             AS DIV_TOTAL
     FROM BCRC.VIEW_BOATSALES_N@BCRCDBLINK;
COMMENT ON TABLE USRBM.VIEW_SALES_BCRC_BOAT IS '부산 경정 매출액';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.RACEYY IS '기준년도';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.RACETIMES IS '회차';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.RACEDAYS IS '일차';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.CYCLECD IS '시행처(099:미사리)';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.RACENO IS '경주번호';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.OUTSITE IS '지점(101:광복,102:서면,005:본장 전자카드,006:광복 전자카드)';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.WIN IS '단승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.PLACE IS '연승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.EXACTA IS '쌍승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.QUINELLA IS '복승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.TRIELLA IS '삼복승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.REFUND IS '환급액';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.DIV_TOTAL IS '지점 매출액';

COMMENT ON COLUMN USRBM.VIEW_SALES_BCRC_BOAT.RACEDATE IS '경주일자';
