DROP VIEW USRBM.VIEW_ITOUCH_SALES_CCRC;

/* Formatted on 2017-03-18 오전 10:53:57 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VIEW_ITOUCH_SALES_CCRC
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_DAY,
   RACE_NO,
   COMM_NO,
   WIN,
   PLC,
   EX,
   QU,
   TRL,
   DIV_TOTAL,
   SALES_CNT
)
AS
   SELECT "RCYEAR" AS STND_YEAR,
          RCTIMES AS TMS,
          RCDAYS AS DAY_ORD,
          RCDATE AS RACE_DAY,
          RACENO AS RACE_NO,
          DECODE (TRACKCD, '003', '004', '099', '003', TRACKCD) MEET_CD,
          BRANCHCD AS COMM_NO,
          "WIN",
          "PLC",
          "EX",
          "QU",
          "TRL",
          (win + plC + ex + qu + trl) DIV_TOTAL,
          (CWIN + CPLC + CEX + CQU + CTRL) AS SALES_CNT
     FROM ccrc.VIEW_ITOUCH_SALES@ccrclink;
COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.TMS IS '회차';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.RACE_DAY IS '경주일';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.COMM_NO IS '지점코드';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.WIN IS '단승식';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.PLC IS '연승식';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.EX IS '쌍승식';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.QU IS '복승식';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.TRL IS '삼복승식';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.DIV_TOTAL IS '매출액';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.SALES_CNT IS '발매건수';

COMMENT ON COLUMN USRBM.VIEW_ITOUCH_SALES_CCRC.MEET_CD IS '시행처';
