DROP VIEW USRBM.VIEW_SALES_CCRC;

/* Formatted on 2017-03-18 오전 10:56:14 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VIEW_SALES_CCRC
(
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_DAY,
   MEET_CD,
   RACE_NO,
   SELL_CD,
   COMM_NO,
   WIN,
   PLA,
   EXA,
   QUI,
   TRI,
   TOT_SALES
)
AS
   SELECT "RACEYY",
          RACETIMES "RACETIMES",
          "RACEDAYS",
          "RACEDATE",
          DECODE (RJANGCD, '003', '004', '099', '003', RJANGCD) AS RJANGCD,
          "RACENO",
          DECODE (TRACKCD,
                  '003', '04',
                  '099', '03',
                  '001', '01',
                  '002', '02',
                  TRACKCD),
          BRANCHCD,
          "WIN",
          "PLA",
          "EXA",
          "QUI",
          "TRI",
          (win + pla + exa + qui + tri)
     FROM ccrc.view_sales@ccrclink;
COMMENT ON TABLE USRBM.VIEW_SALES_CCRC IS '창원 매출액';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.TMS IS '회차';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.RACE_DAY IS '경주일자';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.MEET_CD IS '시행처(001:광명, 002:창원,003:미사리,004:부산)';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.RACE_NO IS '경주';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.SELL_CD IS '판매처(001:광명, 002:창원,003:미사리,004:부산)';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.COMM_NO IS '지점코드(001:본장,002:김해,004;본장전자카드)';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.WIN IS '단승';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.PLA IS '연승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.EXA IS '복승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.QUI IS '쌍승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.TRI IS '삼복승식';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.TOT_SALES IS '매출액';

COMMENT ON COLUMN USRBM.VIEW_SALES_CCRC.STND_YEAR IS '경주년도';
