DROP VIEW USRBM.VW_CALLCT_USER;

/* Formatted on 2017-03-18 ¿ÀÀü 10:57:40 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_CALLCT_USER
(
   USER_SPEC_ID,
   USER_PASSWORD,
   USER_NAME,
   USER_TEL,
   USER_CELL_TEL,
   USER_EMAIL_ID
)
AS
   (SELECT USER_ID USER_SPEC_ID,
           PSWD USER_PASSWORD,
           USER_NM USER_NAME,
           TEL_NO USER_TEL,
           HP_NO USER_CELL_TEL,
           EMAIL USER_EMAIL_ID
      FROM TBRK_USER
     WHERE TEAM_CD = 'GA124950');


GRANT SELECT ON USRBM.VW_CALLCT_USER TO INTRA;

GRANT SELECT ON USRBM.VW_CALLCT_USER TO VWRBM;
