DROP VIEW USRBM.VW_CRS_SALES_BATH;

/* Formatted on 2017-03-18 오전 10:58:03 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_CRS_SALES_BATH
(
   RACE_DAY,
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_NO,
   SELL_CD,
   DIV_TOTAL,
   WIN,
   PLACE,
   EXACTA,
   QUINELLA,
   TRIELLA
)
AS
     SELECT B.RACE_DAY,
            A.MEET_CD,
            A.STND_YEAR,
            A.TMS,
            A.DAY_ORD,
            A.RACE_NO,
            A.SELL_CD,
            SUM (A.NET_AMT) * 100 DIV_TOTAL,
            SUM (DECODE (POOL_CD, '001', A.NET_AMT, 0)) * 100 WIN,
            SUM (DECODE (POOL_CD, '002', A.NET_AMT, 0)) * 100 PLACE,
            SUM (DECODE (POOL_CD, '004', A.NET_AMT, 0)) * 100 EXACTA,
            SUM (DECODE (POOL_CD, '005', A.NET_AMT, 0)) * 100 QUINELLA,
            SUM (DECODE (POOL_CD, '006', A.NET_AMT, 0)) * 100 TRIELLA
       FROM VW_PC_PAYOFFS A, VW_SDL_INFO B
      WHERE     1 = 1
            AND A.STND_YEAR = B.STND_YEAR
            AND A.MEET_CD = B.MEET_CD
            AND A.TMS = B.TMS
            AND A.DAY_ORD = B.DAY_ORD
            AND A.MEET_CD = '001'
   GROUP BY B.RACE_DAY,
            A.MEET_CD,
            A.STND_YEAR,
            A.TMS,
            A.DAY_ORD,
            A.RACE_NO,
            A.SELL_CD;
COMMENT ON TABLE USRBM.VW_CRS_SALES_BATH IS '경주별/승식별 광명경륜매출액(배치)';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.RACE_DAY IS '경주일';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.DIV_TOTAL IS '총매출액';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.WIN IS '단승식 매출액';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.PLACE IS '연승식 매출액';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.EXACTA IS '쌍승식 매출액';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.QUINELLA IS '복승식 총매출액';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_BATH.TRIELLA IS '삼복승식 매출액';


GRANT SELECT ON USRBM.VW_CRS_SALES_BATH TO BCRC;

GRANT SELECT ON USRBM.VW_CRS_SALES_BATH TO CCRC;
