DROP VIEW USRBM.VW_CRS_SALES_REAL;

/* Formatted on 2017-03-18 오전 10:58:14 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_CRS_SALES_REAL
(
   RACE_DAY,
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_NO,
   SELL_CD,
   DIV_TOTAL
)
AS
     SELECT B.RACE_DAY,
            A.MEET_CD,
            A.STND_YEAR,
            A.TMS,
            A.DAY_ORD,
            A.RACE_NO,
            A.SELL_CD,
            SUM (A.DIV_TOTAL) DIV_TOTAL
       FROM TBES_SDL_DT A, VW_SDL_INFO B
      WHERE     1 = 1
            AND A.STND_YEAR = B.STND_YEAR
            AND A.MEET_CD = B.MEET_CD
            AND A.TMS = B.TMS
            AND A.DAY_ORD = B.DAY_ORD
            AND A.MEET_CD = '001'
   GROUP BY B.RACE_DAY,
            A.MEET_CD,
            A.STND_YEAR,
            A.TMS,
            A.DAY_ORD,
            A.RACE_NO,
            A.SELL_CD;
COMMENT ON TABLE USRBM.VW_CRS_SALES_REAL IS '경주별 광명경륜매출액(실시간)';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.RACE_DAY IS '경주일자';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_CRS_SALES_REAL.DIV_TOTAL IS '총매출액';


GRANT SELECT ON USRBM.VW_CRS_SALES_REAL TO BCRC;

GRANT SELECT ON USRBM.VW_CRS_SALES_REAL TO CCRC;
