DROP VIEW USRBM.VW_CHA_SALES_CRA;

/* Formatted on 2017-03-18 ¿ÀÀü 10:57:52 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_CHA_SALES_CRA
(
   RACE_DAY,
   MEET_CD,
   RACE_NO,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   WIN,
   PLACE,
   EXACTA,
   QUINELLA,
   TRIELLA,
   POOL_TOTAL
)
AS
   SELECT RACEDATE AS RACE_DAY,
          CYCLECD AS MEET_CD,
          RACENO AS RACE_NO,
          '02' SELL_CD,
          '01' COMM_NO,
          SUBSTR (OUTSITE, 2, 2) AS DIV_NO,
          WIN,
          PLACE,
          EXACTA,
          QUINELLA,
          TRIELLA,
          WIN + PLACE + EXACTA + QUINELLA + TRIELLA AS POOL_TOTAL
     FROM CCRC.VIEW_CYCLESALES@CCRCLINK;
