DROP VIEW USRBM.VW_DW_SELLST;

/* Formatted on 2017-03-18 오전 10:58:25 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_DW_SELLST
(
   YEAR_DATE,
   STND_YEAR,
   DATE_TOTE,
   SESSION_NO,
   MEET_CD,
   PERF_NO,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   WIN_TYPE,
   RACE_NO,
   NUM_1,
   AMT_1,
   NUM_2,
   AMT_2,
   NUM_3,
   AMT_3,
   NUM_4,
   AMT_4,
   NUM_5,
   AMT_5,
   NUM_6,
   AMT_6,
   NUM_7,
   AMT_7,
   NUM_8,
   AMT_8,
   NUM_9,
   AMT_9,
   NUM_10,
   AMT_10,
   NUM_11,
   AMT_11,
   NUM_12,
   AMT_12,
   NUM_13,
   AMT_13,
   NUM_14,
   AMT_14,
   NUM_15,
   AMT_15,
   NUM_16,
   AMT_16,
   NUM_17,
   AMT_17,
   NUM_18,
   AMT_18,
   NUM_19,
   AMT_19,
   NUM_20,
   AMT_20,
   NUM_21,
   AMT_21,
   NUM_22,
   AMT_22,
   NUM_23,
   AMT_23,
   NUM_TOTAL,
   AMT_TOTAL,
   INST_ID,
   INST_DT,
   UPDT_ID,
   UPDT_DT
)
AS
   SELECT YEAR_DATE,
          STND_YEAR,
          DATE_TOTE,
          SESSION_NO,
          MEET_CD,
          PERF_NO,
          SELL_CD,
          COMM_NO,
          DIV_NO,
          WIN_TYPE,
          RACE_NO,
          NUM_1,
          AMT_1,
          NUM_2,
          AMT_2,
          NUM_3,
          AMT_3,
          NUM_4,
          AMT_4,
          NUM_5,
          AMT_5,
          NUM_6,
          AMT_6,
          NUM_7,
          AMT_7,
          NUM_8,
          AMT_8,
          NUM_9,
          AMT_9,
          NUM_10,
          AMT_10,
          NUM_11,
          AMT_11,
          NUM_12,
          AMT_12,
          NUM_13,
          AMT_13,
          NUM_14,
          AMT_14,
          NUM_15,
          AMT_15,
          NUM_16,
          AMT_16,
          NUM_17,
          AMT_17,
          NUM_18,
          AMT_18,
          NUM_19,
          AMT_19,
          NUM_20,
          AMT_20,
          NUM_21,
          AMT_21,
          NUM_22,
          AMT_22,
          NUM_23,
          AMT_23,
          NUM_TOTAL,
          AMT_TOTAL,
          INST_ID,
          INST_DT,
          UPDT_ID,
          UPDT_DT
     FROM pc_sellst@dw01link;
COMMENT ON COLUMN USRBM.VW_DW_SELLST.YEAR_DATE IS '년도월일';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.STND_YEAR IS '년도 YEAR_TOTE';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.DATE_TOTE IS '일자';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.SESSION_NO IS '세션번호 SESS_NO';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.MEET_CD IS '경륜장코드 LOCATION_NO';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.PERF_NO IS '퍼포먼스번호';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.SELL_CD IS '장소_ASSO  ASSOCIATION_NO';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.COMM_NO IS '장소_지점 ';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.DIV_NO IS '장소_투표소DIV';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.WIN_TYPE IS '창구구분 1:유인 3:무인  5:계좌발매 7:계좌환급';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.RACE_NO IS '경기번호';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_1 IS '구간100 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_1 IS '구간100 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_2 IS '구간200~1,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_2 IS '구간200~1,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_3 IS '구간1,100~5,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_3 IS '구간1,100~5,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_4 IS '구간5,100~9,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_4 IS '구간5,100~9,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_5 IS '구간10,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_5 IS '구간10,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_6 IS '구간10,100~19,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_6 IS '구간10,100~19,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_7 IS '구간20,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_7 IS '구간20,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_8 IS '구간20,100~29,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_8 IS '구간20,100~29,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_9 IS '구간30,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_9 IS '구간30,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_10 IS '구간30,100~39,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_10 IS '구간30,100~39,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_11 IS '구간400,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_11 IS '구간400,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_12 IS '구간40,100 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_12 IS '구간40,100 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_13 IS '구간50,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_13 IS '구간50,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_14 IS '구간50,100~59,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_14 IS '구간50,100~59,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_15 IS '구간60,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_15 IS '구간60,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_16 IS '구간60,100~69,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_16 IS '구간60,100~69,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_17 IS '구간70,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_17 IS '구간70,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_18 IS '구간70,100~79,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_18 IS '구간70,100~79,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_19 IS '구간80,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_19 IS '구간80,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_20 IS '구간80,100~89,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_20 IS '구간80,100~89,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_21 IS '구간90,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_21 IS '구간90,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_22 IS '구간90,100~99,900 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_22 IS '구간90,100~99,900 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_23 IS '구간100,000 매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_23 IS '구간100,000 금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.NUM_TOTAL IS '총매수';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.AMT_TOTAL IS '총금액';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.INST_ID IS '작성자';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.UPDT_ID IS '수정자';

COMMENT ON COLUMN USRBM.VW_DW_SELLST.UPDT_DT IS '수정일시';
