DROP VIEW USRBM.VW_EV_TOTAL_RSLT;

/* Formatted on 2017-03-18 오전 10:58:50 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_EV_TOTAL_RSLT
(
   ESTM_YEAR,
   ESTM_NUM,
   EMP_NO,
   EMP_NM,
   DEPT_NM,
   WK_JOB_NM,
   CNTR_ITM_NM,
   TOT_SCR,
   TOT_GRD
)
AS
   SELECT ESTM_YEAR,
          ESTM_NUM,
          EMP_NO,
          EMP_NM,
          DEPT_NM,
          WK_JOB_NM,
          CNTR_ITM_NM,
          TOT_SCR,
          TOT_GRD
     FROM TBRF_EV_TOTAL_RSLT;
COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.ESTM_YEAR IS '평가년도';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.ESTM_NUM IS '평가회차';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.EMP_NO IS '사번';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.EMP_NM IS '성명';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.DEPT_NM IS '부서명';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.WK_JOB_NM IS '보직명';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.CNTR_ITM_NM IS '보직분야명';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.TOT_SCR IS '최종평점';

COMMENT ON COLUMN USRBM.VW_EV_TOTAL_RSLT.TOT_GRD IS '평가등급';


GRANT SELECT ON USRBM.VW_EV_TOTAL_RSLT TO ACCT;
