DROP VIEW USRBM.VW_MYCAT_SALES;

/* Formatted on 2017-03-18 오전 10:59:33 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_MYCAT_SALES
(
   RACE_DAY,
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_NO,
   POOL_CD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   TOTAL_AMT,
   REFUND,
   NET_AMT,
   AMOUNT1,
   AMOUNT2,
   AMOUNT3,
   AMOUNT4,
   AMOUNT5,
   AMOUNT6,
   AMOUNT7,
   AMOUNT8,
   COUNT1,
   COUNT2,
   COUNT3,
   COUNT4,
   COUNT5,
   COUNT6,
   COUNT7,
   COUNT8
)
AS
   (  SELECT RACE_DAY,
             MEET_CD,
             STND_YEAR,
             TMS,
             DAY_ORD,
             RACE_NO,
             POOL_CD,
             SELL_CD,                 --SELL_CD:01로 통일 "TOTE SYSTEM" 전송 데이터 기준
             COMM_NO,                          --본장:01, 지점:07 ==> 모두 '06'으로 통일
             DIV_NO,       --앞으로 지점별구분을 위해서 COMM_NO가 사용되지만, 현시스템에서는 DIV_NO를 사용
             SUM (TOTAL_AMT) TOTAL_AMT,
             SUM (REFUND) REFUND,
             SUM (NET_AMT) NET_AMT,
             SUM (AMOUNT1) / 100 AMOUNT1,
             SUM (AMOUNT2) / 100 AMOUNT2,
             SUM (AMOUNT3) / 100 AMOUNT3,
             SUM (AMOUNT4) / 100 AMOUNT4,
             SUM (AMOUNT5) / 100 AMOUNT5,
             SUM (AMOUNT6) / 100 AMOUNT6,
             SUM (AMOUNT7) / 100 AMOUNT7,
             SUM (AMOUNT8) / 100 AMOUNT8,
             SUM (COUNT1) COUNT1,
             SUM (COUNT2) COUNT2,
             SUM (COUNT3) COUNT3,
             SUM (COUNT4) COUNT4,
             SUM (COUNT5) COUNT5,
             SUM (COUNT6) COUNT6,
             SUM (COUNT7) COUNT7,
             SUM (COUNT8) COUNT8
        FROM (SELECT RACE_DAY,
                     MEET_CD,
                     STND_YEAR,
                     TMS,
                     DAY_ORD,
                     RACE_NO,
                     POOL_CD,
                     SELL_CD,         --SELL_CD:01로 통일 "TOTE SYSTEM" 전송 데이터 기준
                     '06' COMM_NO,             --본장:01, 지점:07 ==> 모두 '06'으로 통일
                     DECODE (COMM_NO, '01', '00', DIV_NO) DIV_NO, --앞으로 지점별구분을 위해서 COMM_NO가 사용되지만, 현시스템에서는 DIV_NO를 사용
                     TOTAL_AMT,
                     REFUND,
                     NET_AMT,
                     AMOUNT1,
                     AMOUNT2,
                     AMOUNT3,
                     AMOUNT4,
                     AMOUNT5,
                     AMOUNT6,
                     AMOUNT7,
                     AMOUNT8,
                     COUNT1,
                     COUNT2,
                     COUNT3,
                     COUNT4,
                     COUNT5,
                     COUNT6,
                     COUNT7,
                     COUNT8
                FROM V_MYCAT_SALES@CYBETLINK)
    GROUP BY RACE_DAY,
             MEET_CD,
             STND_YEAR,
             TMS,
             DAY_ORD,
             RACE_NO,
             POOL_CD,
             SELL_CD,
             COMM_NO,
             DIV_NO);
