DROP VIEW USRBM.VW_PC_TAX;

/* Formatted on 2017-03-18 ¿ÀÀü 11:04:43 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_TAX
(
   PAY_YEAR,
   MEET_CD,
   SELL_CD,
   TSN,
   PERF_NO,
   COMM_NO,
   DIV_NO,
   REFUND,
   SELL_AMT,
   JIGEUP_AMT,
   COST,
   GITA1,
   GITA2,
   GITA_PAY,
   ETC,
   DOC_MGMT_NO,
   JIK_ID,
   JIK_INPUT_DT,
   PRINT_DT,
   DUMP_DT,
   CUST_NAME,
   CUST_SSN,
   CUST_ADDR,
   CUST_TEL,
   JIGEUP_DT,
   VALID,
   ERR_CHK,
   F_SSN,
   INST_ID,
   INST_DT,
   UPDT_ID,
   UPDT_DT
)
AS
   SELECT PAY_YEAR,
          MEET_CD,
          SELL_CD,
          TSN,
          PERF_NO,
          DECODE (SELL_CD, '03', '98', COMM_NO) AS COMM_NO,
          DIV_NO,
          REFUND,
          SELL_AMT,
          JIGEUP_AMT,
          COST,
          GITA1,
          GITA2,
          GITA_PAY,
          ETC,
          DOC_MGMT_NO,
          JIK_ID,
          JIK_INPUT_DT,
          PRINT_DT,
          DUMP_DT,
          CUST_NAME,
          CUST_SSN,
          CUST_ADDR,
          CUST_TEL,
          JIGEUP_DT,
          VALID,
          ERR_CHK,
          F_SSN,
          INST_ID,
          INST_DT,
          UPDT_ID,
          UPDT_DT
     FROM TBJI_PC_TAX;
