DROP VIEW USRBM.VW_PC_GITA_CRS;

/* Formatted on 2017-03-18 ¿ÀÀü 11:00:53 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_GITA_CRS
(
   MEET_CD,
   SELL_CD,
   JIGEUP_DT,
   GITA1,
   GITA2
)
AS
   (  SELECT A.MEET_CD,
             A.SELL_CD,
             A.JIGEUP_DT,
             SUM (A.GITA1) GITA1,
             SUM (A.GITA2) GITA2
        FROM TBJI_PC_GITA A, (  SELECT JIGEUP_DT, MAX (VERI) VERI
                                  FROM TBJI_PC_GITA_VERI
                              GROUP BY JIGEUP_DT) B
       WHERE 1 = 1 AND A.JIGEUP_DT = B.JIGEUP_DT AND B.VERI = '001'
    GROUP BY A.MEET_CD, A.SELL_CD, A.JIGEUP_DT);


GRANT SELECT ON USRBM.VW_PC_GITA_CRS TO ACCT;

GRANT SELECT ON USRBM.VW_PC_GITA_CRS TO BCRC;

GRANT SELECT ON USRBM.VW_PC_GITA_CRS TO CCRC;
