DROP VIEW USRBM.VW_PC_SATLIT_SUM;

/* Formatted on 2017-03-18 오전 11:03:37 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_SATLIT_SUM
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   TOTAL_AMT,
   REFUND,
   NET_AMT,
   INST_DT,
   UPDT_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           B.COMM_NO,
           B.DIV_NO,
           B.TOTAL_AMT,
           B.REFUND,
           B.NET_AMT,
           B.INST_DT,
           NVL (B.UPDT_DT, B.INST_DT)
      FROM TBJI_PC_FILE_VERI A, TBJI_PC_SATLIT_SUM B
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001');
COMMENT ON TABLE USRBM.VW_PC_SATLIT_SUM IS '지점별/승식별 매출액 합계';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.MEET_CD IS 'Meet Code';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.SELL_CD IS '판매처 코드';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.DIV_NO IS 'Division번호';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.TOTAL_AMT IS '총매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.REFUND IS '환불액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.NET_AMT IS '순매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_SUM.UPDT_DT IS '수정일시';


GRANT SELECT ON USRBM.VW_PC_SATLIT_SUM TO ACCT;
