DROP VIEW USRBM.VW_PC_TELMP;

/* Formatted on 2017-03-18 오전 11:04:53 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_TELMP
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   WIN_NO,
   WIN_TYPE,
   TELLER_ID,
   TELLER_TYPE,
   PERF_NO,
   SESSION_NO,
   SOLD_NUM,
   CASH_NUM,
   CNCL_NUM,
   SOLD_AMT,
   CASH_AMT,
   CNCL_AMT,
   INST_DT,
   UPDT_DT,
   RACE_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           B.COMM_NO,
           B.DIV_NO,
           B.WIN_NO,
           B.WIN_TYPE,
           B.TELLER_ID,
           B.TELLER_TYPE,
           B.PERF_NO,
           B.SESSION_NO,
           B.SOLD_NUM,
           B.CASH_NUM,
           B.CNCL_NUM,
           B.SOLD_AMT,
           B.CASH_AMT,
           B.CNCL_AMT,
           B.INST_DT,
           NVL (B.UPDT_DT, B.INST_DT),
           RACE_DT
      FROM TBJI_PC_FILE_VERI A, TBJI_PC_TELMP B
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001');
COMMENT ON TABLE USRBM.VW_PC_TELMP IS '경주권 판매금액(환불금액포함)';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.COMM_NO IS '발매지점';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.DIV_NO IS '투표소';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.WIN_NO IS '창구번호';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.WIN_TYPE IS '창구형태';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.TELLER_ID IS '발매원번호';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.TELLER_TYPE IS '발매원형태';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.PERF_NO IS '퍼포먼스번호';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.SESSION_NO IS '세션번호';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.SOLD_NUM IS '경주권판매매수';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.CASH_NUM IS '경주권환급매수';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.CNCL_NUM IS '경주권취소매수';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.SOLD_AMT IS '경주권판매금액';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.CASH_AMT IS '경주권환급금액';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.CNCL_AMT IS '경주권취소금액';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.UPDT_DT IS '수정일시';

COMMENT ON COLUMN USRBM.VW_PC_TELMP.RACE_DT IS '발매일자';


GRANT SELECT ON USRBM.VW_PC_TELMP TO ACCT;

GRANT SELECT ON USRBM.VW_PC_TELMP TO INTRA;

GRANT SELECT ON USRBM.VW_PC_TELMP TO VWRBM;
