DROP VIEW USRBM.VW_PC_SATLIT_GSUM;

/* Formatted on 2017-03-18 오전 11:03:27 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_SATLIT_GSUM
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   RACE_NO,
   POOL_CD,
   TOTAL_AMT,
   REFUND,
   NET_AMT,
   INST_DT,
   UPDT_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           CASE WHEN B.COMM_NO = '06' THEN C.CD_NM2 ELSE B.COMM_NO END
              AS COMM_NO,
           CASE WHEN B.COMM_NO = '06' THEN '01' ELSE B.DIV_NO END AS DIV_NO,
           B.RACE_NO,
           B.POOL_CD,
           B.TOTAL_AMT,
           B.REFUND,
           B.NET_AMT,
           B.INST_DT,
           NVL (B.UPDT_DT, B.INST_DT)
      FROM TBJI_PC_FILE_VERI A, TBJI_PC_SATLIT B, TBRK_SPEC_CD C
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001'
           AND B.DIV_NO = C.CD(+)
           AND C.GRP_CD(+) = '127');
COMMENT ON TABLE USRBM.VW_PC_SATLIT_GSUM IS '지점별/승시별 매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.COMM_NO IS '투표소';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.DIV_NO IS '발매지점';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.POOL_CD IS '승식';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.TOTAL_AMT IS '총매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.REFUND IS '환불금액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.NET_AMT IS '순매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT_GSUM.UPDT_DT IS '수정일시';


GRANT SELECT ON USRBM.VW_PC_SATLIT_GSUM TO ACCT;

GRANT SELECT ON USRBM.VW_PC_SATLIT_GSUM TO INTRA;

GRANT SELECT ON USRBM.VW_PC_SATLIT_GSUM TO VWRBM;
