DROP VIEW USRBM.VW_PC_WINNMP;

/* Formatted on 2017-03-18 오전 11:05:06 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_WINNMP
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   WIN_NO,
   WIN_TYPE,
   TELLER_ID,
   TELLER_TYPE,
   SOLD_NUM,
   CASH_NUM,
   CNCL_NUM,
   SOLD_AMT,
   CASH_AMT,
   CNCL_AMT,
   LEAD_CNT,
   RECE_CNT,
   LEAD_AMT,
   RECE_AMT,
   CASH_LEAD_CNT,
   CASH_RECE_CNT,
   CASH_LEAD_AMT,
   CASH_RECE_AMT,
   ACCNT_RECE_CNT,
   ACCNT_DRAW_CNT,
   ACCNT_RECE_AMT,
   ACCNT_DRAW_AMT,
   ACCNT_OPEN_CNT,
   ACCNT_CNCL_CNT,
   ACCNT_OPEN_AMT,
   ACCNT_CNCL_AMT,
   FRST_TM_STAMT,
   LAST_TM_STAMT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           B.COMM_NO,
           B.DIV_NO,
           B.WIN_NO,
           B.WIN_TYPE,
           B.TELLER_ID,
           B.TELLER_TYPE,
           B.SOLD_NUM,
           B.CASH_NUM,
           B.CNCL_NUM,
           B.SOLD_AMT,
           B.CASH_AMT,
           B.CNCL_AMT,
           B.LEAD_CNT,
           B.RECE_CNT,
           B.LEAD_AMT,
           B.RECE_AMT,
           B.CASH_LEAD_CNT,
           B.CASH_RECE_CNT,
           B.CASH_LEAD_AMT,
           B.CASH_RECE_AMT,
           B.ACCNT_RECE_CNT,
           B.ACCNT_DRAW_CNT,
           B.ACCNT_RECE_AMT,
           B.ACCNT_DRAW_AMT,
           B.ACCNT_OPEN_CNT,
           B.ACCNT_CNCL_CNT,
           B.ACCNT_OPEN_AMT,
           B.ACCNT_CNCL_AMT,
           B.FRST_TM_STAMT,
           B.LAST_TM_STAMT
      FROM TBJI_PC_FILE_VERI A, TBJI_PC_WINNMP B
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001');
COMMENT ON TABLE USRBM.VW_PC_WINNMP IS '구매권판매금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.COMM_NO IS '투표소';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.DIV_NO IS '발매지점';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.WIN_NO IS '창구번호';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.WIN_TYPE IS '창구형태';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.TELLER_ID IS '발매원번호';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.TELLER_TYPE IS '발매원형태';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.SOLD_NUM IS '구매권판매매수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_NUM IS '구매권환급매수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CNCL_NUM IS '구매권취소매수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.SOLD_AMT IS '구매권판매금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_AMT IS '구매권환급금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CNCL_AMT IS '구매권취소금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.LEAD_CNT IS '전도건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.RECE_CNT IS '입금건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.LEAD_AMT IS '전도금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.RECE_AMT IS '입금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_LEAD_CNT IS '환급전도건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_RECE_CNT IS '환급입금건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_LEAD_AMT IS '환급전도금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.CASH_RECE_AMT IS '환급입금금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_RECE_CNT IS '구좌입금건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_DRAW_CNT IS '구좌해지건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_RECE_AMT IS '구좌입금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_DRAW_AMT IS '구좌인출액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_OPEN_CNT IS '구좌개설건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_CNCL_CNT IS '구좌해지건수';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_OPEN_AMT IS '구좌개설금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.ACCNT_CNCL_AMT IS '구좌해지금액';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.FRST_TM_STAMT IS '최초구좌실행일시';

COMMENT ON COLUMN USRBM.VW_PC_WINNMP.LAST_TM_STAMT IS '최종구좌실행일시';


GRANT SELECT ON USRBM.VW_PC_WINNMP TO ACCT;

GRANT SELECT ON USRBM.VW_PC_WINNMP TO INTRA;

GRANT SELECT ON USRBM.VW_PC_WINNMP TO VWRBM;
