DROP VIEW USRBM.VW_PC_SATLIT;

/* Formatted on 2017-03-18 오전 11:03:16 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_PC_SATLIT
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   RACE_NO,
   POOL_CD,
   TOTAL_AMT,
   REFUND,
   NET_AMT,
   INST_DT,
   UPDT_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           B.COMM_NO,
           B.DIV_NO,
           B.RACE_NO,
           B.POOL_CD,
           B.TOTAL_AMT,
           B.REFUND,
           B.NET_AMT,
           B.INST_DT,
           NVL (B.UPDT_DT, B.INST_DT)
      FROM TBJI_PC_FILE_VERI A, TBJI_PC_SATLIT B
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001');
COMMENT ON TABLE USRBM.VW_PC_SATLIT IS '지점별/승시별 매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.MEET_CD IS '경륜장코드';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.SELL_CD IS '운영처';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.COMM_NO IS '투표소';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.DIV_NO IS '발매지점';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.POOL_CD IS '승식';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.TOTAL_AMT IS '총매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.REFUND IS '환불금액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.NET_AMT IS '순매출액';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_PC_SATLIT.UPDT_DT IS '수정일시';


GRANT SELECT ON USRBM.VW_PC_SATLIT TO ACCT;

GRANT SELECT ON USRBM.VW_PC_SATLIT TO INTRA;

GRANT SELECT ON USRBM.VW_PC_SATLIT TO VWRBM;
