DROP VIEW USRBM.VW_SDL_DT_SUM_GSUM;

/* Formatted on 2017-03-18 오전 11:07:03 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_SDL_DT_SUM_GSUM
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   SELL_CD,
   COMM_NO,
   DIV_NO,
   DIV_TOTAL,
   REFUND,
   INST_DT,
   UPDT_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.SELL_CD,
           CASE WHEN B.COMM_NO = '06' THEN C.CD_NM2 ELSE B.COMM_NO END
              AS COMM_NO,
           CASE WHEN B.COMM_NO = '06' THEN '01' ELSE B.DIV_NO END AS DIV_NO,
           B.DIV_TOTAL,
           B.REFUND,
           B.INST_DT,
           NVL (B.UPDT_DT, B.INST_DT)
      FROM TBJI_PC_FILE_VERI A, TBES_SDL_DT_SUM B, TBRK_SPEC_CD C
     WHERE     1 = 1
           AND A.FILE_VERI = '001'
           AND A.VERI = '001'
           AND A.STND_YEAR = B.STND_YEAR
           AND A.MEET_CD = B.MEET_CD
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND C.GRP_CD(+) = '127'
           AND C.CD(+) = B.DIV_NO);
COMMENT ON TABLE USRBM.VW_SDL_DT_SUM_GSUM IS '실시간 지점별 매출액(지점별합계)';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.MEET_CD IS 'Meet Code';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.SELL_CD IS '판매처 코드';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.COMM_NO IS 'Community번호';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.DIV_NO IS 'Division번호';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.DIV_TOTAL IS 'Division Total Amount';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.REFUND IS '환불액';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_SDL_DT_SUM_GSUM.UPDT_DT IS '수정일시';


GRANT SELECT ON USRBM.VW_SDL_DT_SUM_GSUM TO ACCT;
