DROP VIEW USRBM.VW_SALES_KBOAT_FLYING;

/* Formatted on 2017-03-18 오전 11:05:49 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_SALES_KBOAT_FLYING
(
   STND_YEAR,
   MEET_CD,
   TMS,
   DAY_ORD,
   RACE_NO,
   RACE_DAY
)
AS
     SELECT STND_YEAR,
            '003' AS MEET_CD,
            TMS,
            DAY_ORD,
            RACE_NO,
            RACE_DAY
       FROM TBED_RACE_VOIL_ACT@MRASYSLINK A, TBEC_RACER_MASTER@MRASYSLINK R
      WHERE     1 = 1
            AND MBR_CD = '001'
            AND VOIL_CD IN ('110', '120')
            AND A.RACER_NO = R.RACER_NO
   GROUP BY STND_YEAR,
            TMS,
            DAY_ORD,
            RACE_NO,
            RACE_DAY;
COMMENT ON TABLE USRBM.VW_SALES_KBOAT_FLYING IS '플라잉 경주';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.MEET_CD IS '시행처코드';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.RACE_NO IS '경주수(플라잉이 발생한 경주)';

COMMENT ON COLUMN USRBM.VW_SALES_KBOAT_FLYING.RACE_DAY IS '경주일자';
