DROP VIEW USRBM.VW_SDL_PT;

/* Formatted on 2017-03-18 오전 11:07:24 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_SDL_PT
(
   MEET_CD,
   STND_YEAR,
   TMS,
   DAY_ORD,
   RACE_NO,
   POOL_CD,
   POOL_TOTAL,
   REFUND,
   INST_ID,
   INST_DT,
   UPDT_ID,
   UPDT_DT
)
AS
   (SELECT B.MEET_CD,
           B.STND_YEAR,
           B.TMS,
           B.DAY_ORD,
           B.RACE_NO,
           B.POOL_CD,
           B.POOL_TOTAL,
           B.REFUND,
           B.INST_ID,
           B.INST_DT,
           B.UPDT_ID,
           NVL (B.UPDT_DT, B.INST_DT)
      FROM TBJI_PC_FILE_VERI A, TBES_SDL_PT B
     WHERE     1 = 1
           AND A.MEET_CD = B.MEET_CD
           AND A.STND_YEAR = B.STND_YEAR
           AND A.TMS = B.TMS
           AND A.DAY_ORD = B.DAY_ORD
           AND A.FILE_VERI = '001'
           AND A.VERI = '001');
COMMENT ON TABLE USRBM.VW_SDL_PT IS '실시간 승식별 매출액';

COMMENT ON COLUMN USRBM.VW_SDL_PT.MEET_CD IS 'Meet Code';

COMMENT ON COLUMN USRBM.VW_SDL_PT.STND_YEAR IS '기준년도';

COMMENT ON COLUMN USRBM.VW_SDL_PT.TMS IS '회차';

COMMENT ON COLUMN USRBM.VW_SDL_PT.DAY_ORD IS '일차';

COMMENT ON COLUMN USRBM.VW_SDL_PT.RACE_NO IS '경주번호';

COMMENT ON COLUMN USRBM.VW_SDL_PT.POOL_CD IS '승식';

COMMENT ON COLUMN USRBM.VW_SDL_PT.POOL_TOTAL IS 'Total Amount';

COMMENT ON COLUMN USRBM.VW_SDL_PT.REFUND IS '환불액';

COMMENT ON COLUMN USRBM.VW_SDL_PT.INST_ID IS '작성자ID';

COMMENT ON COLUMN USRBM.VW_SDL_PT.INST_DT IS '작성일시';

COMMENT ON COLUMN USRBM.VW_SDL_PT.UPDT_ID IS '수정자ID';

COMMENT ON COLUMN USRBM.VW_SDL_PT.UPDT_DT IS '수정일시';


GRANT SELECT ON USRBM.VW_SDL_PT TO ACCT;

GRANT SELECT ON USRBM.VW_SDL_PT TO INTRA;

GRANT SELECT ON USRBM.VW_SDL_PT TO VWRBM;
