DROP VIEW USRBM.VW_USER;

/* Formatted on 2017-03-18 오전 11:09:33 (QP5 v5.136.908.31019) */
CREATE OR REPLACE FORCE VIEW USRBM.VW_USER
(
   GBN,
   USER_ID,
   PSWD,
   USER_NM,
   EMAIL,
   TEL_NO,
   HP_NO,
   FLOC,
   FGRADE,
   ASSO_CD,
   DEPT_CD,
   TEAM_CD,
   ASSO_NM,
   DEPT_NM,
   TEAM_NM
)
AS
   SELECT DECODE (GBN, '005', '001', '002') GBN,
          USER_ID,
          PSWD,
          USER_NM,
          EMAIL,
          TEL_NO,
          HP_NO,
          FLOC,
          FGRADE,
          TRIM (ASSO_CD),
          TRIM (DEPT_CD),
          TRIM (TEAM_CD),
          ASSO_NM,
          DEPT_NM,
          TEAM_NM
     FROM TBRK_USER;
COMMENT ON COLUMN USRBM.VW_USER.GBN IS '구분코드(002:임시사용자,003:평가사용자(투표소장),005:직원)';

COMMENT ON COLUMN USRBM.VW_USER.USER_ID IS '사용자ID';

COMMENT ON COLUMN USRBM.VW_USER.PSWD IS '비밀번호';

COMMENT ON COLUMN USRBM.VW_USER.USER_NM IS '사용자명';

COMMENT ON COLUMN USRBM.VW_USER.EMAIL IS '이메일';

COMMENT ON COLUMN USRBM.VW_USER.TEL_NO IS '전화번호';

COMMENT ON COLUMN USRBM.VW_USER.FLOC IS '직위';

COMMENT ON COLUMN USRBM.VW_USER.FGRADE IS '직급';

COMMENT ON COLUMN USRBM.VW_USER.ASSO_CD IS '대분류코드';

COMMENT ON COLUMN USRBM.VW_USER.DEPT_CD IS '부서코드';

COMMENT ON COLUMN USRBM.VW_USER.TEAM_CD IS '팀코드';

COMMENT ON COLUMN USRBM.VW_USER.ASSO_NM IS '대분류명';

COMMENT ON COLUMN USRBM.VW_USER.DEPT_NM IS '부서명';

COMMENT ON COLUMN USRBM.VW_USER.TEAM_NM IS '팀명';


GRANT SELECT ON USRBM.VW_USER TO APPLER;
