/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-11-09 04:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.of.message;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hanaph.gw.pe.member.vo.MemberVO;
import com.hanaph.gw.of.message.vo.MessageVO;
import com.hanaph.gw.co.common.utils.RequestFilterUtil;
import com.hanaph.gw.co.fileAttach.vo.FileAttachVO;
import com.hanaph.gw.co.common.utils.WebUtil;
import com.hanaph.gw.pe.member.vo.MemberVO;
import javax.servlet.http.HttpSession;
import com.hanaph.gw.pe.member.vo.MemberVO;
import java.util.List;
import com.hanaph.gw.co.menu.vo.MenuVO;
import java.util.ArrayList;
import com.hanaph.gw.co.menu.vo.MenuVO;
import com.hanaph.gw.co.common.utils.StringUtil;
import java.util.List;

public final class messageList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1424677116691L));
    _jspx_dependants.put("/common/path.jsp", Long.valueOf(1429838623000L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1418202584955L));
    _jspx_dependants.put("/include/lnb.jsp", Long.valueOf(1444971460463L));
    _jspx_dependants.put("/include/gnb.jsp", Long.valueOf(1444976197526L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1434416046480L));
    _jspx_dependants.put("/include/location.jsp", Long.valueOf(1418692302668L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
com.hanaph.gw.co.common.utils.Environment env = new com.hanaph.gw.co.common.utils.Environment();
	
	String HTTPS_GROUP_WEB_ROOT = env.getValue("https.web_root_dir.url");
	String HTTPS_GROUP_ROOT = env.getValue("https.root_dir.url");
	String GROUP_WEB_ROOT = env.getValue("web_root_dir.url");
	String GROUP_ROOT = env.getValue("root_dir.url");
	String JDBC_URL = env.getValue("jdbc.url");
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<MessageVO> messageList = (List<MessageVO>)request.getAttribute("messageList"); //쪽지 리스트
	List<FileAttachVO> attachList = (List<FileAttachVO>)request.getAttribute("attachList"); //첨부파일 리스트
	List<MemberVO> authorityMemberList = (List<MemberVO>)request.getAttribute("authorityMemberList"); //삭제,DB삭제 권한을 가진 임직원
	String emp_no = StringUtil.nvl((String)request.getAttribute("emp_no"));
	
	String seq = StringUtil.nvl((String)request.getAttribute("seq")); //메세지 시퀀스
	String search_read_yn = (String)request.getAttribute("search_read_yn"); //검색키워드
	String searchKeyword = (String)request.getAttribute("searchKeyword"); //검색키워드
	String searchType = StringUtil.nvl((String)request.getAttribute("searchType"),"contents"); //검색타입
	String start_ymd = StringUtil.nvl((String)request.getAttribute("start_ymd")); //조회기간
	String end_ymd = StringUtil.nvl((String)request.getAttribute("end_ymd")); //조회기간
	String type = StringUtil.nvl((String)request.getAttribute("type")); //받은,보낸쪽지함 구분
	String str = ""; //받은,보낸 문구
	
	searchKeyword = StringUtil.nvl(RequestFilterUtil.toHtmlTagReplace("", searchKeyword));
	
	String searchDate[] = WebUtil.dateCal(0);
	
	if("1".equals(type)){
		str = "받은";
	}else{
		str = "보낸";
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>하나제약 그룹웨어</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/fonts.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/dtree.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/css/smoothness/jquery-ui-1.10.4.custom.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery-ui-1.10.4.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/jquery.bpopup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/default.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/dtree.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/js/formCheck.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar fileArr = [];\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t");
if(!"".equals(seq)){
      out.write("\r\n");
      out.write("\t\t\t\tmessageDetail('");
      out.print(seq);
      out.write("');\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t$(\"#search_read_yn > option[value=");
      out.print(search_read_yn);
      out.write("]\").attr(\"selected\",\"true\");\r\n");
      out.write("\t\t\t$(\"#searchType > option[value=");
      out.print(searchType);
      out.write("]\").attr(\"selected\",\"true\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 검색\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction goSearch(){\r\n");
      out.write("\t\t\tif(formCheck.containsChars(document.getElementById(\"searchKeyword\").value, \"%\")){\r\n");
      out.write("\t\t\t\t alert(\"특수문자를 사용할수 없습니다\");\r\n");
      out.write("\t\t\t\t return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(formCheck.dateChk($(\"#start_ymd\").val(),$(\"#end_ymd\").val())<0){\r\n");
      out.write("\t\t\t\talert(\"쪽지기간 시작 날짜가 쪽지기간 종료 날짜 보다 이후 입니다.\");\r\n");
      out.write("\t\t\t\tstart_ymd.focus();\r\n");
      out.write("\t\t\t\treturn\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.frm.type.value = \"");
      out.print(type);
      out.write("\";\r\n");
      out.write("\t\t\tdocument.frm.action = \"");
      out.print(GROUP_ROOT);
      out.write("/of/message/messageList.do\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 전체선택\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction allCheck2(){\r\n");
      out.write("\t\t\t$(\"input[name=allCheck]:checkbox\").each(function() {\r\n");
      out.write("\t    \t\tif($(this).is(':checked')) {\r\n");
      out.write("\t                $(\"input[name=check]\").prop(\"checked\", true);\r\n");
      out.write("\t            } else {\r\n");
      out.write("\t                $(\"input[name=check]\").prop(\"checked\", false);\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 삭제(플래그처리)\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction deleteMessage(){\r\n");
      out.write("\t\t\tvar message_seq = \"\";\r\n");
      out.write("\t\t\t$(\"input[name='check']:checkbox:checked\").each(function(){\r\n");
      out.write("\t\t\t\tmessage_seq += $(this).val()+\"|\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"input[name='check']:checkbox:checked\").length < 1){\r\n");
      out.write("\t\t\t\talert(\"삭제할 대상을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(confirm(\"삭제 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\t\tdocument.frm.message_seq.value = message_seq;\r\n");
      out.write("\t\t\t\tdocument.frm.action = \"");
      out.print(GROUP_ROOT);
      out.write("/of/message/deleteMessage.do\";\r\n");
      out.write("\t\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 DB삭제\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction deleteMessageDB(){\r\n");
      out.write("\t\t\tvar message_seq = \"\";\r\n");
      out.write("\t\t\t$(\"input[name='check']:checkbox:checked\").each(function(){\r\n");
      out.write("\t\t\t\tmessage_seq += $(this).val()+\"|\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"input[name='check']:checkbox:checked\").length < 1){\r\n");
      out.write("\t\t\t\talert(\"삭제할 대상을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(confirm(\"DB에서 데이터를 삭제합니다.\\n그래도 삭제 하시겠습니까?\") == true){\t\r\n");
      out.write("\t\t\t\tdocument.frm.message_seq.value = message_seq;\r\n");
      out.write("\t\t\t\tdocument.frm.action = \"");
      out.print(GROUP_ROOT);
      out.write("/of/message/deleteMessageDB.do\";\r\n");
      out.write("\t\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 상세정보\r\n");
      out.write("\t\t * @param message_seq\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction messageDetail(message_seq){\r\n");
      out.write("\t\t\t$(\"#contents\"+message_seq).attr(\"class\",\"bt_none list_txt\");\r\n");
      out.write("\t\t\tvar receiveNm = \"\";\r\n");
      out.write("\t\t\tvar file_nm = \"\";\r\n");
      out.write("\t\t\tvar file_list= '<th class=\"bb_none\">첨부파일</th><td class=\"append_file01 br_none\"><div class=\"append_list\"><span id=\"fileNm\" class=\"attachList\"></span></div></td>';\r\n");
      out.write("\t\t\tvar file_list_print= '<th class=\"bb_none\">첨부파일</th><td class=\"append_file01 br_none\"><div class=\"append_list\"><span id=\"fileNmPrint\"></span></div></td>';\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(GROUP_ROOT);
      out.write("/of/message/messageDetail.do\",\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tdata:{message_seq:message_seq},\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i<data.list.length;i++){\r\n");
      out.write("\t\t\t\t\t\t//receiveNm += data.list[i].emp_ko_nm+\"(\"+data.list[i].dept_ko_nm +\" / \"+ data.list[i].grad_ko_nm+\")\";\r\n");
      out.write("\t\t\t\t\t\treceiveNm += data.list[i].emp_ko_nm;\r\n");
      out.write("\t\t\t\t\t\tif(data.list.length-1 != i ){\r\n");
      out.write("\t\t\t\t\t\t\treceiveNm += \", \";\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfor(var j=0; j<data.attachList.length; j++){\r\n");
      out.write("\t\t\t\t\t\tfile_nm += \"<p><img src='");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/img_file.png' />&nbsp;<a href='");
      out.print(GROUP_ROOT);
      out.write("/fileDownload.do?file_seq=\"+data.attachList[j].file_seq+\"&filename=\"+data.attachList[j].file_nm+\"&filePath=\"+data.attachList[j].file_path+\"'>\"+data.attachList[j].origin_file_nm+\"</a><p>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (data.attachList.length > 1) {\r\n");
      out.write("\t\t\t\t\t\tfile_nm += \"<p><button type='button' onclick=\\\"javascript:Commons.fileDownloadAll(0);\\\">전체 다운로드</button><p>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.attachList.length == 0){\r\n");
      out.write("\t\t\t\t\t\tfile_list = \"\";\r\n");
      out.write("\t\t\t\t\t\tfile_list_print = \"\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#fileList\").html(file_list);\r\n");
      out.write("\t\t\t\t\t$(\"#receiveNm\").text(receiveNm);\r\n");
      out.write("\t\t\t\t\t$(\"#sendNm\").text(data.emp_ko_nm);\r\n");
      out.write("\t\t\t\t\t$(\"#contents\").html(data.contents);\r\n");
      out.write("\t\t\t\t\t$(\"#fileNm\").html(file_nm);\r\n");
      out.write("\t\t\t\t\t/* 인쇄 영역 */\r\n");
      out.write("\t\t\t\t\t$(\"#sendNmPrint\").text(data.emp_ko_nm);\r\n");
      out.write("\t\t\t\t\t$(\"#fileListPrint\").html(file_list_print);\r\n");
      out.write("\t\t\t\t\t$(\"#fileNmPrint\").html(file_nm);\r\n");
      out.write("\t\t\t\t\t$(\"#createDtPrint\").text(data.create_dt);\r\n");
      out.write("\t\t\t\t\t$(\"#contentsPrint\").html(data.contents);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지 인쇄 팝업\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction printPopup(){\r\n");
      out.write("\t\t\tif($(\"#contents\").text() == \"\"){\r\n");
      out.write("\t\t\t\talert(\"쪽지 제목을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tCommons.previewOpen('message', '803', '768');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 쪽지함 읽은 임직원 레이어 팝업\r\n");
      out.write("\t\t * @param message_seq\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction messageReadData(message_seq){\r\n");
      out.write("\t\t\t$('#messageReadData').bPopup({\r\n");
      out.write("\t\t\t\tcontent:'iframe', //'ajax', 'iframe' or 'image'\r\n");
      out.write("\t\t\t\tiframeAttr:'scrolling=\"no\" frameborder=\"0\" width=\"550px\" height=\"295px\"',\r\n");
      out.write("\t\t\t\tfollow: [true, true],\r\n");
      out.write("\t\t\t\tcontentContainer:'.message_content',\r\n");
      out.write("\t\t\t\tmodalClose: true,\r\n");
      out.write("\t            opacity: 0.6,\r\n");
      out.write("\t            positionStyle: 'fixed',\r\n");
      out.write("\t\t\t\tloadUrl:'");
      out.print(GROUP_ROOT );
      out.write("/of/common/commonReadData.do?seq=' + message_seq + '&type=MESSAGE',\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 레이어팝업 닫기\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction layerClose(){ \r\n");
      out.write("\t\t\t$('#messageReadData').bPopup().close();\r\n");
      out.write("\t\t\t$('#getMember').bPopup().close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * 메세지 전달시 대상가져오는 팝업 - type=MESSAGE_DELIVER\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction getMember(message_seq){\r\n");
      out.write("\t\t\tdocument.frm.message_seq.value = message_seq;\r\n");
      out.write("\t\t\t$('#getMember').bPopup({\r\n");
      out.write("\t\t\t\tcontent:'iframe', //'ajax', 'iframe' or 'image'\r\n");
      out.write("\t\t\t\tiframeAttr:'scrolling=\"yes\" frameborder=\"0\" width=\"617px\" height=\"'+$(window).innerHeight()+'px\"',\r\n");
      out.write("\t\t\t\tfollow: [true, true],\r\n");
      out.write("\t\t\t\tcontentContainer:'.member_content',\r\n");
      out.write("\t\t\t\tmodalClose: true,\r\n");
      out.write("\t            opacity: 0.6,\r\n");
      out.write("\t            positionStyle: 'fixed',\r\n");
      out.write("\t\t\t\tloadUrl:'");
      out.print(GROUP_ROOT );
      out.write("/pe/member/memberSelectPopup.do?type=MESSAGE_DELIVER&seq='+message_seq,\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 반드시 addMemberRow 로 function 만들어 테이블 상황에 맞게 테이블 생성한다. */\r\n");
      out.write("\t\t/**\r\n");
      out.write("\t\t * @param obj\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction addMemberRow(obj){\r\n");
      out.write("\t\t\tvar target_empNo = \"\";\r\n");
      out.write("\t\t\t for(var i=0; i<obj.length; i++){\r\n");
      out.write("\t\t    \tif(obj[i].checked){\r\n");
      out.write("\t\t\t    \tvar objParam = obj[i].value;\r\n");
      out.write("\t\t\t\t\tvar memberListValueArr = objParam.split(\"|\");\r\n");
      out.write("\t\t\t\t\ttarget_empNo += memberListValueArr[0]+\"|\"; \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tif(confirm(\"전달 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\t\tdocument.frm.target_empNo.value = target_empNo;\r\n");
      out.write("\t\t\t\tdocument.frm.type.value = 3;\r\n");
      out.write("\t\t\t\tdocument.frm.action=\"");
      out.print(GROUP_ROOT);
      out.write("/of/message/insertMessage.do\";\r\n");
      out.write("\t\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\twindow.parent.layerClose();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t *기존 row 삭제 \r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction memberRemove(){\r\n");
      out.write("\t\t \t$('#tbl tr input').remove();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction replyMessage(seq){\r\n");
      out.write("\t\t\tdocument.frm.message_seq.value = seq;\r\n");
      out.write("\t\t\tdocument.frm.action=\"");
      out.print(GROUP_ROOT);
      out.write("/of/message/messageReplyWrite.do\";\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	HttpSession headerSession = request.getSession(false);	
	MemberVO headerMemberVO = (MemberVO) headerSession.getAttribute("gwUser");

      out.write('\r');
      out.write('\n');

	String user_id ="";
	String pass="";

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction logOut(){\r\n");
      out.write("\t\tif(confirm(\"로그아웃 하시겠습니까?\")){\r\n");
      out.write("\t\t\t location.href = \"");
      out.print(GROUP_ROOT);
      out.write("/co/login/logOut.do\";  // 이동할주소\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap_header\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<h1><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/main/main.do'\"><img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/header_logo.jpg\" alt=\"하나제약 그룹웨어\" /></a></h1>\r\n");
      out.write("\t\t<div class=\"wrap_menu\">\r\n");
      out.write("\t\t\t<span class=\"connect\">");
      out.print(headerMemberVO.getEmp_ko_nm() );
      out.write("</span>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li class=\"first\"><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/pe/member/memberDetail.do'\">내정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"javascript:Commons.popupOpen('passChg', '");
      out.print(GROUP_ROOT);
      out.write("/co/login/passwordChangeForm.do', '290', '239'); return false;\">비밀번호변경</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"javascript:logOut(); return false;\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/of/notice/noticeList.do?search_start_ymd=2015-01-01&search_read_yn=N'\">공지 ");
      out.print(headerMemberVO.getNoticeCountNoread() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/of/message/messageList.do?start_ymd=2015-01-01&type=1&search_read_yn=N'\">받은쪽지 ");
      out.print(headerMemberVO.getMessageReceiveCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/receive/receiveList.do?search_start_ymd=2015-01-01&search_appr_state=E03001'\">문서결재 ");
      out.print(headerMemberVO.getReceiveCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/implement/implementList.do?search_start_dt=2015-01-01&approval_type=E03001&search_read_yn=N'\">시행결재중 ");
      out.print(headerMemberVO.getImplementOngoingCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/ea/implement/implementList.do?search_start_dt=2015-01-01&approval_type=E03002&search_read_yn=N'\">시행완료 ");
      out.print(headerMemberVO.getImplementCompleteCount() );
      out.write("</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- 20150609 웹메일 클릭 시 로그인 되지 않도록 수정 -->\r\n");
      out.write("\t\t\t<!-- 원복 시 해당 주석 삭제 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"http://gwmail.hanaph.co.kr/index.php?_user=");
      out.print(headerMemberVO.getE_mail() );
      out.write("\" target=\"_blank\" class=\"webmail\" >WEB MAIL</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<MenuVO> gnbMenuList = (List)headerSession.getAttribute("gwGNB"); 

      out.write("\r\n");
      out.write("<div class=\"wrap_gnb\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");

		if(gnbMenuList.size() > 0){
			for(int i=0; gnbMenuList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = gnbMenuList.get(i);
		
      out.write("\r\n");
      out.write("\t\t<li ");
if(i == 0){ 
      out.write("class=\"first\"");
} 
      out.write("><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(menuVO.getMenu_nm() );
 if("jdbc:oracle:thin:@58.229.234.12:1521:ORCL".equals(JDBC_URL)){ 
      out.write('(');
      out.write('테');
      out.write(')');
} 
      out.write("</a></li>\r\n");
      out.write("\t\t");
	}
		} 
      out.write(" \r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<div class=\"wrap_con\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<MenuVO> lnbMentList = (List<MenuVO>)request.getAttribute("lnbMenuList");
	if(lnbMentList == null){
		lnbMentList = new ArrayList();
	}
	String MENU_CHILD = com.hanaph.gw.co.common.utils.StringUtil.nvl((String)request.getAttribute("MENU_CHILD"), "01");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"location\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\" onclick=\"location.href='");
      out.print(GROUP_ROOT);
      out.write("/main/main.do'\"><img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/location_icon_home.gif\" alt=\"home\" /></a> > </li>\r\n");
      out.write("\t\t");

		if(lnbMentList.size()!=0){
			
			for(int i=0; lnbMentList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = lnbMentList.get(i);
				if(menuVO.getMenu_child().equals(MENU_CHILD)){
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"#\">");
      out.print(menuVO.getParents_menu_nm() );
      out.write("</a> > </li>\r\n");
      out.write("\t\t<li><a href=\"");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl() );
      out.write("\" class=\"active\">");
      out.print(menuVO.getMenu_nm() );
      out.write("</a></li>\r\n");
      out.write("\t\t");

				}
			}
		}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"lnb\">\r\n");
      out.write("\t");

		if(lnbMentList.size()!=0){
			MenuVO menuVO = new MenuVO();
			menuVO = lnbMentList.get(0);
	
      out.write("\r\n");
      out.write("\t<p class=\"tit\">");
      out.print(StringUtil.nvl(menuVO.getParents_menu_nm()) );
      out.write("</p>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");

		if(lnbMentList.size()!=0){
			for(int i=0; lnbMentList.size()>i;i++){
				MenuVO menuVO = new MenuVO();
				menuVO = lnbMentList.get(i);
		
      out.write("\r\n");
      out.write("\t\t<li ");
if(i==lnbMentList.size()-1){ 
      out.write(" class=\"last\"");
} 
      out.write(">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(GROUP_ROOT );
      out.print(menuVO.getUrl() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t");
if(menuVO.getMenu_child().length() == 6) {
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;ㄴ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print(StringUtil.nvl(menuVO.getMenu_nm()));
      out.write("\t\r\n");
      out.write("\t\t\t\t<span class=\"none_check\">&nbsp;");
      out.print(StringUtil.nvl(menuVO.getAdd_menu_nm()));
      out.write("</span>\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");

			}
		}
		
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"cont float_left\">\r\n");
      out.write("\t\t\t\t<h2>");
      out.print(str );
      out.write(" 쪽지함</h2>\r\n");
      out.write("\t\t\t\t<div class=\"noticeboard_box\">\r\n");
      out.write("\t\t\t\t<form id=\"frm\" name=\"frm\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"message_seq\" name=\"message_seq\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"type\" name=\"type\" value=\"");
      out.print(type );
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"target_empNo\" name=\"target_empNo\" />\r\n");
      out.write("\t\t\t\t<div class=\"serch_box\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"serch_con01\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sc_txt\">조회기간</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"serch_date_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"start_ymd\" name=\"start_ymd\" class=\"serch_date\" value=\"");
      out.print(start_ymd );
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn_date\" type=\"button\"><span class=\"blind\">날짜선택</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t</span> ~ \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"serch_date_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"end_ymd\" name=\"end_ymd\" class=\"serch_date\" value=\"");
      out.print(end_ymd );
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn_date\" type=\"button\"><span class=\"blind\">날짜선택</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t");
if("1".equals(type)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sc_txt\">열람여부</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"serch_select01\" id=\"search_read_yn\" name=\"search_read_yn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"all\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Y\">읽음</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"N\">안읽음</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont02\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sc_txt\">쪽지함 검색</span>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"serch_select02\" id=\"searchType\" name=\"searchType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"subject\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"createNo\">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"serch_txt\" id=\"searchKeyword\" value=\"");
      out.print(searchKeyword);
      out.write("\" name=\"searchKeyword\" maxlength=\"32\" onKeyPress=\"if(event.keyCode=='13'){goSearch(); return false;}\" >\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<span class=\"serch_btn\" onclick=\"javascript:goSearch();\"><button type=\"button\">검색</button></span>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"list_btn\">\r\n");
      out.write("\t\t\t\t\t<div class=\"list_button\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"type_01\" type=\"button\" onclick=\"javascript:deleteMessage();\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t");

						if(authorityMemberList != null){
							for(int i=0; authorityMemberList.size()>i;i++){
								MemberVO memberVO = new MemberVO();
								memberVO = authorityMemberList.get(i);
								if(emp_no.equals(memberVO.getEmp_no())){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"type_01\" type=\"button\" onclick=\"javascript:deleteMessageDB();\">DB삭제</button>\r\n");
      out.write("\t\t\t\t\t\t");

								}
							}
						} 
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"type_01\" type=\"button\" onclick=\"javascripr:printPopup();\">미리보기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"list_t\">* 총 건수:<span class=\"none_check\">");
      out.print(StringUtil.makeMoneyType(messageList.size()) );
      out.write("</span>건</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cont_box cont_table05\">\r\n");
      out.write("\t\t\t\t<table class=\"over\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:31px;\" />\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:72px;\" />\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:338px;\" />\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:154px;\" />\r\n");
      out.write("\t\t\t\t\t\t");
if("1".equals(type)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:61px;\" />\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:61px;\" />\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:81px;\" />\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"allCheck\" name=\"allCheck\" onclick=\"javascript:allCheck2();\" /></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>보낸이</th>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"border-bottom: none;\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>보낸일시</th>\r\n");
      out.write("\t\t\t\t\t\t\t");
if("1".equals(type)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>전달</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>답장</th>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th>읽은 수</th>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"br_none\">첨부</th>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\t\r\n");
      out.write("\t\t\t\t\t<tbody>\t\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"in_table\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"7\" class=\"br_none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cont_table05 ofy_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:31px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:72px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:338px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:154px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if("1".equals(type)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:61px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:61px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:81px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(messageList.size()!=0){
										String contents = "";
										for(int i=0; messageList.size()>i; i++){
											MessageVO messageVO = new MessageVO();
											messageVO=messageList.get(i);
											contents = messageVO.getContents();
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write("><input type=\"checkbox\" id=\"check\" name=\"check\" value=\"");
      out.print(messageVO.getMessage_seq() );
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td onclick=\"javascript:Commons.memberPopup('");
      out.print(messageVO.getCreate_no() );
      out.write("');\" ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write('>');
      out.print(messageVO.getEmp_ko_nm() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"txtleft\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"word-wrap:break-word; white-space:normal; display:inline-block; width:317px;\" id=\"contents");
      out.print(messageVO.getMessage_seq());
      out.write("\" onclick=\"javascript:messageDetail('");
      out.print(messageVO.getMessage_seq());
      out.write("');\" ");
if("N".equals(messageVO.getRead_yn()) && "1".equals(type)){
      out.write("class=\"");
if(0==i){
      out.write("bt_none ");
}
      out.write(" list_txt none_check\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("class=\"");
if(0==i){
      out.write("bt_none ");
}
      out.write("list_txt\"");
}
      out.write('>');
      out.print(StringUtil.nvl(RequestFilterUtil.toHtmlTagReplace("", messageVO.getSubject())) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span>");
      out.print(messageVO.getCreate_dt() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
if("1".equals(type)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write("><button type=\"button\" class=\"type_01\" onclick=\"javascript:getMember('");
      out.print(messageVO.getMessage_seq());
      out.write("');\">전달</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write("><button type=\"button\" class=\"type_01\" onclick=\"javascript:replyMessage('");
      out.print(messageVO.getMessage_seq());
      out.write("');\">답장</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td onclick=\"javascript:messageReadData('");
      out.print(messageVO.getMessage_seq() );
      out.write("')\" ");
if(0 == i){
      out.write(" class=\"bt_none\"");
}
      out.write('>');
      out.print(messageVO.getRead_cnt() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td ");
if(0 == i){
      out.write(" class=\"bt_none br_none\"");
}
      out.write(" class=\"br_none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
if(messageVO.getAttach_cnt() > 0){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(GROUP_WEB_ROOT);
      out.write("/img/img_file.png\" alt=\"파일첨부\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									}else{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr><td class=\"br_none\" colspan=\"6\">쪽지가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table style=\"table-layout: fixed;\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"82px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"492px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"ts_reset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>보낸이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"sendNm\" class=\"br_none\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"ts_reset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>받는이</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"max_height br_none\"><div id=\"receiveNm\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"txt_box_re\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"br_none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"contents\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"ts_reset\" id=\"fileList\">\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<!-- 인쇄 영역 -->\r\n");
      out.write("\t\t\t\t<div class=\"cont_box cont_table06\" id=\"message\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th colspan=\"4\">받 은 쪽 지</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>보 낸 이  : </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"3\" id=\"sendNmPrint\" class=\"br_none\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>보낸 시간 : </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"createDtPrint\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>출력 일자 : </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"br_none\">");
      out.print(searchDate[0] );
      out.write("</td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"txt_box_re\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"4\" class=\"br_none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"contentsPrint\" style=\"word-wrap:break-word; white-space:normal; width:745px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"ts_reset\" id=\"fileListPrint\"></tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 인쇄 영역 끝-->\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='messageReadData' style='display:none; width:auto; height:auto; '>\r\n");
      out.write("\t\t<div class='message_content'></div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='getMember' style='display:none; width:auto; height:auto; '>\r\n");
      out.write("\t\t<div class='member_content'></div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap_foot\">\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\tCopyright ⓒ 2014 <span class=\"copy_fc\">HANA PHARM CO.</span>, LTD. All Right Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
